# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX support
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable parallel builds
org.gradle.parallel=true

# Enable configuration caching
org.gradle.configuration-cache=true
