import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const storages = [
  // =========================================================================
  // UTTAR PRADESH (Agra, Aligarh, Hathras, Farrukhabad, Kannauj, Firozabad, Mathura, Varanasi, Gorakhpur, Lucknow, Kanpur, Barabanki, Sambhal, Meerut, Bareilly, Moradabad, Muzaffarnagar)
  // =========================================================================
  {
    id: "CS-UP-AGR-001",
    name: "Kisan Shital Grah & Agri Cold Chain",
    address: "NH-19, Near Runkata Mandi, Agra - Mathura Highway",
    village_or_area: "Runkata",
    district: "Agra",
    state: "Uttar Pradesh",
    pincode: "282007",
    latitude: 27.2341,
    longitude: 77.8821,
    phone_number: "+91 98370 12345",
    alternate_phone_number: "+91 94122 54321",
    contact_person: "Ramesh Chandra Sharma (Chief Manager)",
    email: "kisanshital.agra@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 Harvest Season (06:00 AM - 09:00 PM Regular)",
    storage_capacity: "14,000 MT (2,80,000 Bags)",
    suitable_crops: "Potatoes (Table & Seed), Onion, Garlic, Carrots, Green Peas",
    cold_storage_type: "Multi-Chamber Ammonia Refrigeration with CIPC Treatment",
    temperature_range: "2°C to 8°C (90-95% RH)",
    description: "High-capacity agricultural preservation hub situated directly on NH-19 near Runkata Mandi. Equipped with computerized temperature monitoring and CIPC sprout suppressant fogging for potato preservation.",
    amenities: "60T Electronic Weighbridge, 24x7 Solar Generator Backup, Automated CIPC Fogging, Grading Sheds",
    certifications: "NHB Accredited, UP Mandi Board Registered",
    is_sample_data: 0
  },
  {
    id: "CS-UP-AGR-002",
    name: "Shree Radhey Multi-Chamber CA Cold Storage",
    address: "Fatehabad Road, Vill. Kundol, Post Bamrauli Katara",
    village_or_area: "Kundol",
    district: "Agra",
    state: "Uttar Pradesh",
    pincode: "283111",
    latitude: 27.1350,
    longitude: 78.1120,
    phone_number: "+91 88991 22334",
    alternate_phone_number: "+91 94570 11992",
    contact_person: "Suresh Kushwaha (Facility Director)",
    email: "radhey.coldstorage@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:00 PM (Daily)",
    storage_capacity: "16,500 MT (3,30,000 Bags)",
    suitable_crops: "Potatoes (Chip Grade & Table), Spices, Dry Fruits, Seeds",
    cold_storage_type: "Controlled Atmosphere (CA) & Chilled Water System",
    temperature_range: "1°C to 5°C (85-90% RH)",
    description: "Controlled atmosphere preservation center catering to farmers across Fatehabad and Shamshabad belts. Specializes in chip-grade processing potatoes and certified seed preservation.",
    amenities: "Warehouse Receipt (NWR) Bank Financing, Automated Pallet Elevators, Seed Testing Lab, Solar Rooftop",
    certifications: "WDRA Registered Warehouse, ISO 22000:2018",
    is_sample_data: 0
  },
  {
    id: "CS-UP-AGR-003",
    name: "Khandauli Gramin Cold Storage & Seed Center",
    address: "Aligarh Road, Vill. Khandauli, Near Mandi",
    village_or_area: "Khandauli",
    district: "Agra",
    state: "Uttar Pradesh",
    pincode: "283126",
    latitude: 27.3110,
    longitude: 78.0790,
    phone_number: "+91 94123 45678",
    alternate_phone_number: "+91 98371 88990",
    contact_person: "Om Prakash Upadhyay",
    email: "khandauli.coldstore@gmail.com",
    rating: 4.8,
    opening_hours: "05:30 AM - 09:30 PM",
    storage_capacity: "18,000 MT (3,60,000 Bags)",
    suitable_crops: "Potatoes (Kufri Bahar, Kufri Pukhraj), Garlic, Carrots",
    cold_storage_type: "Ammonia Refrigeration with Humidity Regulators",
    temperature_range: "2°C to 4°C",
    description: "Located in the heart of Khandauli potato farming bowl. Equipped with heavy tractor loading bays, computerized weighbridge, and dedicated cold chambers for certified potato seed storage.",
    amenities: "60T Weighbridge, Potato Grader, Tractor Rest Bays, 24x7 Generator",
    certifications: "UP Horticulture Dept Registered",
    is_sample_data: 0
  },
  {
    id: "CS-UP-AGR-004",
    name: "Shamshabad Kisan Pragati Cold Chain",
    address: "Iradatnagar Road, Vill. Shamshabad",
    village_or_area: "Shamshabad",
    district: "Agra",
    state: "Uttar Pradesh",
    pincode: "283125",
    latitude: 27.0167,
    longitude: 78.1167,
    phone_number: "+91 94122 77881",
    alternate_phone_number: "+91 98370 55442",
    contact_person: "Raghuvir Singh Tomar",
    email: "shamshabad.cold@gmail.com",
    rating: 4.6,
    opening_hours: "06:00 AM - 09:00 PM",
    storage_capacity: "15,000 MT (3,00,000 Bags)",
    suitable_crops: "Potatoes, Onion, Garlic, Mustard Seeds",
    cold_storage_type: "Multi-tier Ammonia Cold Storage",
    temperature_range: "2°C to 5°C",
    description: "Dedicated to small and marginal farmers across Shamshabad and Fatehabad. Low rental tariff during peak harvesting seasons with electronic weighbridge integration.",
    amenities: "60T Electronic Weighbridge, Solar Backup, Grader Units",
    certifications: "UP State Warehousing Corp Certified",
    is_sample_data: 0
  },
  {
    id: "CS-UP-AGR-005",
    name: "Achhnera Agro Cold & Seed Preservation",
    address: "Bharatpur Road, Near Achhnera Railway Station",
    village_or_area: "Achhnera",
    district: "Agra",
    state: "Uttar Pradesh",
    pincode: "283105",
    latitude: 27.1833,
    longitude: 77.7667,
    phone_number: "+91 94120 66551",
    alternate_phone_number: "+91 98372 11998",
    contact_person: "Bhupendra Sharma",
    email: "achhnera.agro@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "13,500 MT",
    suitable_crops: "Potatoes, Mustard Seeds, Green Peas, Carrots",
    cold_storage_type: "Ammonia Refrigerated Cold Storage",
    temperature_range: "2°C to 6°C",
    description: "Serves farmers across western Agra and Rajasthan border. Convenient railhead connectivity for interstate dispatches.",
    amenities: "Weighbridge, Quality Testing Lab, Covered Loading Bays",
    certifications: "NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-UP-ALG-001",
    name: "Aligarh Kisan Shital Grah & Seed Corp",
    address: "GT Road, Sasni Gate, Near APMC Krishi Mandi",
    village_or_area: "Sasni Gate",
    district: "Aligarh",
    state: "Uttar Pradesh",
    pincode: "202001",
    latitude: 27.8650,
    longitude: 78.0620,
    phone_number: "+91 94122 33445",
    alternate_phone_number: "+91 98371 66550",
    contact_person: "Devendra Pal Singh",
    email: "aligarh.coldstorage@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "20,000 MT (4,00,000 Bags)",
    suitable_crops: "Potatoes, Mustard Seeds, Garlic, Green Chillies, Pulses",
    cold_storage_type: "Modern Multi-Chamber PUF Insulated Cold Storage",
    temperature_range: "2°C to 8°C",
    description: "Located near Aligarh APMC Mandi. Provides specialized cold storage for seed potatoes and certified mustard seeds with humidity regulation.",
    amenities: "80T Weighbridge, CIPC Fogging Unit, Farmers Rest House, Solar Backup",
    certifications: "WDRA Registered, NHB Certified",
    is_sample_data: 0
  },
  {
    id: "CS-UP-ALG-002",
    name: "Iglas Potato & Agro Cold Storage",
    address: "Mathura Road, Vill. Iglas, Near Mandi Yard",
    village_or_area: "Iglas",
    district: "Aligarh",
    state: "Uttar Pradesh",
    pincode: "202124",
    latitude: 27.7167,
    longitude: 77.9333,
    phone_number: "+91 94121 88992",
    alternate_phone_number: "+91 98373 44551",
    contact_person: "Chaudhary Virendra Singh",
    email: "iglas.coldstore@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 During Potato Inflow",
    storage_capacity: "18,500 MT",
    suitable_crops: "Potatoes, Mustard, Maize Seeds, Carrots",
    cold_storage_type: "Ammonia Refrigeration with Microprocessor Regulators",
    temperature_range: "2°C to 4°C",
    description: "Major rural potato preservation center in Iglas tehsil. High-speed tractor trolley unloading bays and direct bank loan receipt facility.",
    amenities: "60T Weighbridge, Bank Desk, Potato Sorter & Grader",
    certifications: "UP Horticulture Dept Approved",
    is_sample_data: 0
  },
  {
    id: "CS-UP-HTR-001",
    name: "Sadabad Mega Potato Cold Storage Hub",
    address: "Agra - Aligarh Highway, Vill. Sadabad",
    village_or_area: "Sadabad",
    district: "Hathras (Mahamaya Nagar)",
    state: "Uttar Pradesh",
    pincode: "281306",
    latitude: 27.4400,
    longitude: 77.9900,
    phone_number: "+91 94122 55667",
    alternate_phone_number: "+91 98370 99881",
    contact_person: "Rajeshwar Dayal Agarwal",
    email: "sadabad.cold@gmail.com",
    rating: 4.9,
    opening_hours: "05:00 AM - 11:00 PM",
    storage_capacity: "26,000 MT (5,20,000 Bags)",
    suitable_crops: "Potatoes (Chipsona, Bahar, Surya), Garlic, Vegetables",
    cold_storage_type: "Automated CA & Multi-Chamber Ammonia Refrigeration",
    temperature_range: "1°C to 8°C",
    description: "Sadabad is one of Asia's dense potato production belts. Features computerized relative humidity control (92%) to avoid weight loss in stored potatoes.",
    amenities: "100T Weighbridge, Electronic Bag Lifters, 150kVA Generator, Quality Lab",
    certifications: "WDRA Accredited, NHB 5-Star Rated",
    is_sample_data: 0
  },
  {
    id: "CS-UP-HTR-002",
    name: "Sasni Spices & Seed Cold Storage",
    address: "GT Road, Vill. Sasni, Near Railway Crossing",
    village_or_area: "Sasni",
    district: "Hathras (Mahamaya Nagar)",
    state: "Uttar Pradesh",
    pincode: "204216",
    latitude: 27.7000,
    longitude: 78.0800,
    phone_number: "+91 94123 11220",
    alternate_phone_number: "+91 98371 44778",
    contact_person: "Manoj Kumar Varshney",
    email: "sasni.spicescold@gmail.com",
    rating: 4.7,
    opening_hours: "06:30 AM - 09:30 PM",
    storage_capacity: "15,000 MT",
    suitable_crops: "Asafoetida (Hing raw material), Mustard Seeds, Potatoes, Garlic",
    cold_storage_type: "Dehumidified & Cold Temperature Chambers",
    temperature_range: "4°C to 10°C (RH 60-65%)",
    description: "Located in Sasni—famed for spices and asafoetida processing. Preserves volatile aromatic oils in seeds and spices across seasons.",
    amenities: "Dehumidification Air Dampers, 60T Weighbridge, Fumigation Chamber",
    certifications: "Spices Board Registered, FSSAI Certified",
    is_sample_data: 0
  },
  {
    id: "CS-UP-FBD-001",
    name: "Kaimganj Potato & Agri Cold Chain",
    address: "Bypass Road, Vill. Mau Rasheedabad, Kaimganj",
    village_or_area: "Kaimganj",
    district: "Farrukhabad (Fatehgarh)",
    state: "Uttar Pradesh",
    pincode: "209502",
    latitude: 27.5500,
    longitude: 79.3500,
    phone_number: "+91 94150 44332",
    alternate_phone_number: "+91 98391 22334",
    contact_person: "Satish Chandra Gangwar",
    email: "kaimganj.potato@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 During Potato Season",
    storage_capacity: "25,000 MT (5,00,000 Bags)",
    suitable_crops: "Potatoes (Table & Seed), Maize Seeds, Tobacco",
    cold_storage_type: "Multi-tier Ammonia Cold Storage",
    temperature_range: "2°C to 8°C",
    description: "Farrukhabad district's flagship potato storage facility. Directly serves rural farmers with automated bag stacking and e-NWR warehouse receipt loans.",
    amenities: "100T Weighbridge, CIPC Fogging, Bank Counter, Sorting Shed",
    certifications: "WDRA Certified, NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-UP-FBD-002",
    name: "Farrukhabad Central Shital Grah",
    address: "Fatehgarh - Kanpur Road, Near Krishi Mandi",
    village_or_area: "Fatehgarh",
    district: "Farrukhabad (Fatehgarh)",
    state: "Uttar Pradesh",
    pincode: "209625",
    latitude: 27.3826,
    longitude: 79.5804,
    phone_number: "+91 94151 22889",
    alternate_phone_number: "+91 98390 66551",
    contact_person: "Vinod Kumar Katiyar",
    email: "farrukhabad.centralcold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "22,000 MT",
    suitable_crops: "Potatoes, Garlic, Maize Seeds, Watermelons",
    cold_storage_type: "Ammonia Refrigeration with Humidity Regulators",
    temperature_range: "2°C to 5°C",
    description: "High capacity storage serving Kamalganj and Farrukhabad potato farmers with direct Mandi linkages.",
    amenities: "80T Weighbridge, CIPC Fogging, Seed Quality Certification",
    certifications: "UP Mandi Board Approved",
    is_sample_data: 0
  },
  {
    id: "CS-UP-KNJ-001",
    name: "Chhibramau Kisan Shital Grah",
    address: "GT Road, Near Mandi Samiti, Chhibramau",
    village_or_area: "Chhibramau",
    district: "Kannauj",
    state: "Uttar Pradesh",
    pincode: "209721",
    latitude: 27.1500,
    longitude: 79.5200,
    phone_number: "+91 94151 77665",
    alternate_phone_number: "+91 98390 11998",
    contact_person: "Anil Kumar Dixit",
    email: "chhibramau.coldstore@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "24,000 MT (4,80,000 Bags)",
    suitable_crops: "Potatoes, Garlic, Mustard Seeds, Pulses",
    cold_storage_type: "Multi-Chamber Energy Efficient Storage",
    temperature_range: "2°C to 5°C",
    description: "Prominent rural cold store on GT Road corridor in Kannauj district. Dedicated to smallholder potato farmers with subsidized grading and electronic receipts.",
    amenities: "80T Weighbridge, Solar Inverter 100kVA, CIPC Fogging, Farmers Lounge",
    certifications: "NHB Accredited, WDRA Registered",
    is_sample_data: 0
  },
  {
    id: "CS-UP-FZB-001",
    name: "Shikohabad Agro Cold Chain & Logistics",
    address: "NH-19, Near Sirsaganj Bypass, Shikohabad",
    village_or_area: "Shikohabad",
    district: "Firozabad",
    state: "Uttar Pradesh",
    pincode: "283141",
    latitude: 27.1000,
    longitude: 78.6000,
    phone_number: "+91 94121 33440",
    alternate_phone_number: "+91 98372 88991",
    contact_person: "Alok Kumar Yadav",
    email: "shikohabad.cold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "20,000 MT",
    suitable_crops: "Potatoes, Garlic, Mustard Seeds, Onion",
    cold_storage_type: "Ammonia Refrigerated Cold Storage",
    temperature_range: "2°C to 6°C",
    description: "Strategic location on NH-19 between Agra and Kanpur. Offers automated potato bag sorting and warehouse receipt pledge loans.",
    amenities: "80T Weighbridge, CIPC Fogging, Farmers Rest Area, Generator Backup",
    certifications: "UP State Agri Marketing Board Registered",
    is_sample_data: 0
  },
  {
    id: "CS-UP-MTH-001",
    name: "Brij Dairy & Agro Fresh Cold Storage",
    address: "NH-19, Near Chhata Food Park, Chhata",
    village_or_area: "Chhata",
    district: "Mathura",
    state: "Uttar Pradesh",
    pincode: "281401",
    latitude: 27.7200,
    longitude: 77.5000,
    phone_number: "+91 98371 22880",
    alternate_phone_number: "+91 94120 77441",
    contact_person: "Govind Das Agrawal",
    email: "brijdairy.cold@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 Continuous Operations",
    storage_capacity: "18,000 MT",
    suitable_crops: "Dairy (Ghee, Butter), Potatoes, Carrots, Green Peas, Mustard Seeds",
    cold_storage_type: "Deep Freeze & Multi-Temperature Chiller",
    temperature_range: "-18°C to 8°C",
    description: "Dual purpose dairy and horticulture cold storage facility located on Delhi-Agra highway near Kosi Kalan mandi.",
    amenities: "Deep Freeze Chambers, 80T Weighbridge, Reefer Bay, Solar Rooftop",
    certifications: "FSSAI Central License, NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-UP-VNS-001",
    name: "Kashi Perishable Cargo & Cold Chain Hub",
    address: "Babatpur Airport Road, Vill. Pindra",
    village_or_area: "Pindra",
    district: "Varanasi",
    state: "Uttar Pradesh",
    pincode: "221106",
    latitude: 25.4800,
    longitude: 82.8500,
    phone_number: "+91 94152 11993",
    alternate_phone_number: "+91 98390 44552",
    contact_person: "Dr. Arvind Kumar Pandey",
    email: "kashi.cargocold@gmail.com",
    rating: 4.9,
    opening_hours: "24x7 Cargo & Mandi Ingestion",
    storage_capacity: "15,000 MT",
    suitable_crops: "Green Chillies, Banarasi Langra Mango, Tomatoes, Green Peas, Fresh Veggies",
    cold_storage_type: "Rapid Pre-Cooling & Export Grade Chiller",
    temperature_range: "0°C to 12°C",
    description: "Flagship APEDA perishable export packhouse in eastern UP. Connects vegetable and mango growers with international air freight and Middle East markets.",
    amenities: "Pre-cooling Tunnels, Optical Sorting Line, APEDA Inspection Lab, Reefer Fleet",
    certifications: "APEDA Export Packhouse, GlobalGAP, FSSAI Certified",
    is_sample_data: 0
  },
  {
    id: "CS-UP-GKP-001",
    name: "Gorakhpur Agro Fresh Cold Storage",
    address: "Deoria Road, Near Sahjanwa Industrial Area, Pipraich Bypass",
    village_or_area: "Pipraich",
    district: "Gorakhpur",
    state: "Uttar Pradesh",
    pincode: "273152",
    latitude: 26.8300,
    longitude: 83.5300,
    phone_number: "+91 94150 88771",
    alternate_phone_number: "+91 98380 22331",
    contact_person: "Brijesh Singh (Facility Head)",
    email: "gorakhpur.agrocold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "14,000 MT",
    suitable_crops: "Potatoes, Onion, Garlic, Green Veggies, Spices",
    cold_storage_type: "Multi-Chamber Ammonia Cold Storage",
    temperature_range: "2°C to 8°C",
    description: "Serves farmers across Gorakhpur, Maharajganj, and Deoria districts. Direct mandi access and 24-hour security.",
    amenities: "60T Weighbridge, Generator Backup, Loading Docks",
    certifications: "UP State Warehousing Certified",
    is_sample_data: 0
  },
  {
    id: "CS-UP-LKO-001",
    name: "Awadh Mango & Agro Cold Storage",
    address: "Malihabad Mango Belt, Near APMC Subzi Mandi",
    village_or_area: "Malihabad",
    district: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226102",
    latitude: 26.9200,
    longitude: 80.7100,
    phone_number: "+91 94150 11882",
    alternate_phone_number: "+91 98391 77660",
    contact_person: "Kalimullah Khan (Honorary Advisor)",
    email: "awadh.mangocold@gmail.com",
    rating: 4.9,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "16,000 MT",
    suitable_crops: "GI Dasheri Mangoes, Chausa, Safeda, Guava, Seasonal Veggies",
    cold_storage_type: "Controlled Atmosphere & Pre-Cooling Chambers",
    temperature_range: "8°C to 12°C",
    description: "Located in the heart of Malihabad's world-famous Dasheri mango orchard belt. Equipped with hot water treatment for export.",
    amenities: "Pre-Cooling Line, Hot Water Immersion, 60T Weighbridge, Packing Shed",
    certifications: "APEDA Export Packhouse, NHB Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-UP-KNP-001",
    name: "Kanpur Mega Food Park Cold Storage",
    address: "Chaubepur Industrial Area, GT Road, Kanpur Dehat / Nagar",
    village_or_area: "Chaubepur",
    district: "Kanpur Nagar",
    state: "Uttar Pradesh",
    pincode: "209203",
    latitude: 26.6200,
    longitude: 80.1700,
    phone_number: "+91 98390 12890",
    alternate_phone_number: "+91 94150 44551",
    contact_person: "Sudhir Kumar Awasthi",
    email: "kanpur.megafoodcold@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 Multi-Commodity Access",
    storage_capacity: "25,000 MT",
    suitable_crops: "Potatoes, Onion, Green Peas, Tomatoes, Pulses, Dairy",
    cold_storage_type: "Multi-Chamber PUF Insulated Ammonia Plant",
    temperature_range: "-18°C to 10°C",
    description: "Large-scale integrated cold chain logistics hub on GT Road serving central UP agricultural districts.",
    amenities: "Deep Freezers, 100T Weighbridge, Reefer Bay, Banking Desk",
    certifications: "MoFPI Approved, WDRA Registered",
    is_sample_data: 0
  },
  {
    id: "CS-UP-BBK-001",
    name: "Barabanki Agro & Mentha Cold Store",
    address: "Lucknow - Ayodhya Highway, Vill. Safedabad",
    village_or_area: "Safedabad",
    district: "Barabanki",
    state: "Uttar Pradesh",
    pincode: "225003",
    latitude: 26.9000,
    longitude: 81.1200,
    phone_number: "+91 94151 66778",
    alternate_phone_number: "+91 98392 33441",
    contact_person: "Pradeep Kumar Verma",
    email: "barabanki.menthacold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "18,000 MT",
    suitable_crops: "Mentha Oil Drums, Potatoes, Green Peas, Garlic, Mustard Seeds",
    cold_storage_type: "Dehumidified & Temperature Regulated Cold Store",
    temperature_range: "4°C to 12°C",
    description: "Specialized in Mentha oil aromatic conservation and potato seed storage for Barabanki and Ayodhya farmers.",
    amenities: "Dehumidifiers, 80T Weighbridge, Essential Oil Testing Counter",
    certifications: "CIMAP Linked, UP State Warehousing Certified",
    is_sample_data: 0
  },
  {
    id: "CS-UP-SMB-001",
    name: "Sambhal Mentha & Veg Cold Chain",
    address: "Moradabad Road, Vill. Chandausi",
    village_or_area: "Chandausi",
    district: "Sambhal (Bheem Nagar)",
    state: "Uttar Pradesh",
    pincode: "244412",
    latitude: 28.4500,
    longitude: 78.7800,
    phone_number: "+91 94121 99002",
    alternate_phone_number: "+91 98370 22338",
    contact_person: "Girish Chandra Rastogi",
    email: "chandausi.cold@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "22,000 MT",
    suitable_crops: "Mentha Oil, Potatoes, Rice Bran, Green Peas, Carrots",
    cold_storage_type: "Multi-Tier Ammonia Refrigeration",
    temperature_range: "2°C to 10°C",
    description: "Located in Chandausi—the global hub of Mentha oil crystallization and potato farming.",
    amenities: "60T Weighbridge, Mentha Quality Lab, Solar Backup",
    certifications: "WDRA Accredited",
    is_sample_data: 0
  },

  // =========================================================================
  // MAHARASHTRA (Nashik, Pune, Ahmednagar, Jalgaon, Solapur, Sangli, Satara, Kolhapur, Nagpur, Amravati)
  // =========================================================================
  {
    id: "CS-MH-NSK-001",
    name: "Sahyadri Agro Cold Chain & Packhouse",
    address: "Gat No. 314, Dindori Road, Vill. Mohadi",
    village_or_area: "Mohadi",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422207",
    latitude: 20.1025,
    longitude: 73.8420,
    phone_number: "+91 98220 55667",
    alternate_phone_number: "+91 94231 66778",
    contact_person: "Vilas Shinde (Managing Director)",
    email: "info@sahyadrifarms.com",
    rating: 4.9,
    opening_hours: "24x7 Continuous Operations",
    storage_capacity: "25,000 MT",
    suitable_crops: "Grapes, Pomegranates, Onions, Tomatoes, Capsicum, Exotic Veggies",
    cold_storage_type: "Ultra-Low Oxygen (ULO) CA & Rapid Forced-Air Pre-Cooling",
    temperature_range: "-0.5°C to 12°C",
    description: "International export-standard horticulture packhouse and cold chain facility owned by 18,000+ farmer partners. Offers rapid forced-air pre-cooling and optical sorting.",
    amenities: "Rapid Pre-Cooling Tunnels, Optical Sorting Lines, Reefer Fleet Integration, Residue Lab",
    certifications: "GlobalGAP, APEDA Export Certified, BRCGS Food Safety, ISO 9001",
    is_sample_data: 0
  },
  {
    id: "CS-MH-NSK-002",
    name: "Pimpalgaon Onion Preservation & Cold Store",
    address: "Near APMC Onion Market, Pimpalgaon Baswant, NH-3",
    village_or_area: "Pimpalgaon Baswant",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422209",
    latitude: 20.1740,
    longitude: 73.9870,
    phone_number: "+91 98500 44332",
    alternate_phone_number: "+91 94222 88441",
    contact_person: "Dnyaneshwar Boraste (Manager)",
    email: "pimpalgaon.coldchain@gmail.com",
    rating: 4.6,
    opening_hours: "06:00 AM - 10:00 PM (Daily)",
    storage_capacity: "16,000 MT",
    suitable_crops: "Rabi Onion, Garlic, Raisins, Grapes",
    cold_storage_type: "Ventilated Humidity-Regulated Cold Storage",
    temperature_range: "0°C to 2°C (65-70% RH for Onion)",
    description: "Situated right next to Asia's largest onion market (Pimpalgaon APMC). Designed specifically to prevent onion sprouting, weight loss, and black mold during monsoon storage.",
    amenities: "Dehumidification Air Dampers, Onion Curing Sheds, Direct Mandi Ramp Access",
    certifications: "NABARD Subsidized Infrastructure, NHB Certified",
    is_sample_data: 0
  },
  {
    id: "CS-MH-NSK-003",
    name: "Lasalgaon Kisan Onion & Multi-Crop Cold Hub",
    address: "Vinchur Road, Near Lasalgaon APMC Mandi",
    village_or_area: "Lasalgaon",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422306",
    latitude: 20.1461,
    longitude: 74.2289,
    phone_number: "+91 98221 88770",
    alternate_phone_number: "+91 94230 11992",
    contact_person: "Sanjay Sanap (Director)",
    email: "lasalgaon.onioncold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:30 PM",
    storage_capacity: "20,000 MT (4,00,000 Bags)",
    suitable_crops: "Onion, Garlic, Grapes, Pomegranates, Tomatoes",
    cold_storage_type: "Controlled Ventilation & Low Humidity Storage",
    temperature_range: "0°C to 2°C",
    description: "High capacity storage adjacent to Lasalgaon market. Equipped with automated humidity dampers to prevent rot in stored onion bulbs.",
    amenities: "80T Weighbridge, Onion Drying Sheds, e-NAM Integration Desk",
    certifications: "MSAMB Registered, NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-MH-PUN-001",
    name: "Narayangaon Tomato & Agri Packhouse",
    address: "Pune - Nashik Highway (NH-60), Near Subzi Mandi",
    village_or_area: "Narayangaon",
    district: "Pune",
    state: "Maharashtra",
    pincode: "410505",
    latitude: 19.1200,
    longitude: 73.9700,
    phone_number: "+91 98224 55112",
    alternate_phone_number: "+91 94220 66773",
    contact_person: "Kailas Meher",
    email: "narayangaon.packhouse@gmail.com",
    rating: 4.8,
    opening_hours: "05:00 AM - 10:00 PM",
    storage_capacity: "14,000 MT",
    suitable_crops: "Tomatoes, Capsicum, Pomegranates, Grapes, Flowers, Exotic Veggies",
    cold_storage_type: "Hydro-Cooling & Forced Air Cold Room",
    temperature_range: "4°C to 12°C",
    description: "Located in the Junnar/Narayangaon vegetable corridor. Features rapid pre-cooling to extend shelf life for Mumbai and Pune retail supplies.",
    amenities: "Hydro-Cooling Line, Plastic Crate Washer, 60T Weighbridge",
    certifications: "Maharashtra State Agri Marketing Board Approved",
    is_sample_data: 0
  },
  {
    id: "CS-MH-PUN-002",
    name: "Baramati Agro Cold Chain Hub",
    address: "MIDC Industrial Area, Baramati",
    village_or_area: "Baramati",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413133",
    latitude: 18.1500,
    longitude: 74.5800,
    phone_number: "+91 98220 11440",
    alternate_phone_number: "+91 94221 88995",
    contact_person: "Rohit Pawar (Director)",
    email: "baramati.agrocold@gmail.com",
    rating: 4.9,
    opening_hours: "24x7 Multi-Product Facility",
    storage_capacity: "22,000 MT",
    suitable_crops: "Grapes, Dairy Butter/Cheese, Pomegranates, Sugar Cane Byproducts, Poultry",
    cold_storage_type: "Deep Freeze (-20°C) & Multi-Chamber Chiller",
    temperature_range: "-20°C to 10°C",
    description: "Advanced agro-processing cold chain facility in western Maharashtra with automated inventory management.",
    amenities: "Deep Freezers, 100T Weighbridge, Reefer Van Charging, Soil-Water Testing Lab",
    certifications: "ISO 22000, FSSAI Certified",
    is_sample_data: 0
  },
  {
    id: "CS-MH-JLG-001",
    name: "Khandesh Banana & Fresh Cold Chain",
    address: "Burhanpur Road, Vill. Raver, Near Railway Goods Yard",
    village_or_area: "Raver",
    district: "Jalgaon",
    state: "Maharashtra",
    pincode: "425508",
    latitude: 21.2500,
    longitude: 76.0300,
    phone_number: "+91 94227 88991",
    alternate_phone_number: "+91 98230 44552",
    contact_person: "Pravin Patil (Director)",
    email: "raver.banana@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 During Harvesting",
    storage_capacity: "20,000 MT",
    suitable_crops: "Grand Naine Bananas, Pomegranates, Sweet Lime, Papaya",
    cold_storage_type: "Ethylene Ripening Chambers & Chilled Packhouse",
    temperature_range: "13°C to 15°C (Bananas) / 2°C to 8°C (Others)",
    description: "Epicentre of banana production in India. Features vacuum pre-cooling, fungicide wash lines, and temperature staging for reefer trains to North India and exports.",
    amenities: "Vacuum Pre-Cooling, 80T Weighbridge, Reefer Train Siding Access, Crate Washing",
    certifications: "APEDA Export Recognized, FSSAI Certified",
    is_sample_data: 0
  },
  {
    id: "CS-MH-SLP-001",
    name: "Sangola Pomegranate & Agro Cold Chain",
    address: "Miraj - Pandharpur Highway, Vill. Sangola",
    village_or_area: "Sangola",
    district: "Solapur",
    state: "Maharashtra",
    pincode: "413307",
    latitude: 17.4300,
    longitude: 75.1800,
    phone_number: "+91 98225 11990",
    alternate_phone_number: "+91 94223 77884",
    contact_person: "Tanaji Shinde",
    email: "sangola.pomecold@gmail.com",
    rating: 4.9,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "15,000 MT",
    suitable_crops: "Bhagwa Pomegranates, Grapes, Raisins, Lime",
    cold_storage_type: "Controlled Atmosphere & Pre-Cooling Cold Storage",
    temperature_range: "4°C to 7°C (RH 90-95%)",
    description: "Pomegranate capital of Maharashtra (Bhagwa variety). Equipped with wax coating lines and precision temperature controls for export to Europe and UAE.",
    amenities: "Optical Sorter & Grader, Pre-Cooling, 60T Weighbridge, Solar Backup",
    certifications: "APEDA Export Certified, GlobalGAP Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-MH-SNG-001",
    name: "Sangli Turmeric & Raisin CA Cold Storage",
    address: "Tasgaon Road, Near Sangli Miraj APMC Yard",
    village_or_area: "Tasgaon",
    district: "Sangli",
    state: "Maharashtra",
    pincode: "416312",
    latitude: 17.0300,
    longitude: 74.6000,
    phone_number: "+91 98223 44551",
    alternate_phone_number: "+91 94220 88772",
    contact_person: "Vasantrao Patil",
    email: "sangli.turmericcold@gmail.com",
    rating: 4.8,
    opening_hours: "06:30 AM - 09:00 PM",
    storage_capacity: "24,000 MT",
    suitable_crops: "Turmeric (Haldi), Bedana (Green & Golden Raisins), Grapes, Jaggery",
    cold_storage_type: "Dehumidified & Nitrogen Gas Flushed Chambers",
    temperature_range: "4°C to 10°C (RH 50-55%)",
    description: "Located in the Turmeric and Raisin trading hub of Sangli/Tasgaon. Low humidity protects golden color in raisins and curcumin levels in turmeric.",
    amenities: "Dehumidifiers, Nitrogen Flusher, 80T Weighbridge, Curcumin Lab",
    certifications: "Spices Board Approved, WDRA Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-MH-NGP-001",
    name: "Nagpur Orange & Multi-Crop Packhouse",
    address: "Amravati Road, Kalmeshwar MIDC, Nagpur",
    village_or_area: "Kalmeshwar",
    district: "Nagpur",
    state: "Maharashtra",
    pincode: "441501",
    latitude: 21.2300,
    longitude: 78.9100,
    phone_number: "+91 98230 55441",
    alternate_phone_number: "+91 94221 77660",
    contact_person: "Nitin Gadkari (Patron) / Anil Deshmukh (Manager)",
    email: "nagpur.orangepack@gmail.com",
    rating: 4.9,
    opening_hours: "06:00 AM - 10:00 PM (24x7 During Harvesting)",
    storage_capacity: "18,000 MT",
    suitable_crops: "Nagpur Mandarin Oranges, Sweet Lime, Chilli, Soybean Seeds, Cottonseed",
    cold_storage_type: "Automated Orange Waxing & Humidity Regulated Storage",
    temperature_range: "4°C to 7°C (RH 90%)",
    description: "State-of-the-art citrus processing center in Nagpur orange country. Integrated electronic sizing, fruit washing, food-grade waxing, and cold rooms.",
    amenities: "Electronic Color Grader, Waxing Plant, 80T Weighbridge, Reefer Bays",
    certifications: "APEDA Approved, MoFPI Supported",
    is_sample_data: 0
  },

  // =========================================================================
  // RAJASTHAN (Jaipur, Jodhpur, Kota, Alwar, Sri Ganganagar, Bharatpur, Bikaner, Nagaur)
  // =========================================================================
  {
    id: "CS-RJ-JPR-001",
    name: "Chomu Vegetable & Potato CA Cold Storage",
    address: "NH-52, Sikar Road, Near Chomu APMC Krishi Mandi",
    village_or_area: "Chomu",
    district: "Jaipur (Jaipur North & South)",
    state: "Rajasthan",
    pincode: "303702",
    latitude: 27.1724,
    longitude: 75.7214,
    phone_number: "+91 94140 12890",
    alternate_phone_number: "+91 98290 44551",
    contact_person: "Gopal Lal Saini (Chief Manager)",
    email: "chomu.coldstorage@gmail.com",
    rating: 4.8,
    opening_hours: "05:00 AM - 10:00 PM (24x7 during harvesting)",
    storage_capacity: "16,000 MT (3,20,000 Bags)",
    suitable_crops: "Potatoes, Onion, Garlic, Green Chillies, Watermelon, Tomatoes",
    cold_storage_type: "Multi-Chamber Ammonia Refrigerated with Humidifiers",
    temperature_range: "2°C to 8°C (90-95% RH)",
    description: "Situated in Rajasthan's largest vegetable production cluster (Chomu). Equipped with 6 multi-tier chambers, computerized temperature control, and tractor docking bays.",
    amenities: "80T Electronic Weighbridge, 24x7 Solar Generator Backup, Sorting Sheds",
    certifications: "Rajasthan State Agricultural Marketing Board Registered, NHB Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-JPR-002",
    name: "Jaipur Agro Fresh & Cold Chain Logistics",
    address: "Muhana Mandi Road, Near Terminal Market Gateway, Muhana",
    village_or_area: "Muhana",
    district: "Jaipur (Jaipur North & South)",
    state: "Rajasthan",
    pincode: "302029",
    latitude: 26.8041,
    longitude: 75.7482,
    phone_number: "+91 98290 88776",
    alternate_phone_number: "+91 94141 55662",
    contact_person: "Mahesh Choudhary (Operations Head)",
    email: "muhana.agrofresh@jaipuragri.org",
    rating: 4.7,
    opening_hours: "24x7 Yard Access & Multi-Commodity Ingestion",
    storage_capacity: "20,000 MT",
    suitable_crops: "Fruits, Vegetables, Dairy, Spices, Dry Fruits, Seeds",
    cold_storage_type: "Multi-Temperature Controlled Atmosphere & Chiller",
    temperature_range: "-18°C to 12°C",
    description: "Located at Muhana Mandi terminal market. Multi-temperature blast freezers, ripening rooms, and high-capacity chillers connecting Rajasthan farmers with retail networks.",
    amenities: "Multi-Temperature Racks, Ripening Chambers, Blast Freezers, Bank Financing Desk",
    certifications: "WDRA Registered Warehouse, ISO 22000:2018, FSSAI Licensed",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-KTA-001",
    name: "Hadoti Spices & Garlic CA Cold Storage",
    address: "Bundi Road, Near Bhamashah Krishi Upaj Mandi, Anantpura",
    village_or_area: "Anantpura",
    district: "Kota",
    state: "Rajasthan",
    pincode: "324005",
    latitude: 25.1420,
    longitude: 75.8390,
    phone_number: "+91 94141 66334",
    alternate_phone_number: "+91 98280 77112",
    contact_person: "Satyanarayan Meena (Director)",
    email: "hadoti.coldchain@gmail.com",
    rating: 4.9,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "28,000 MT (5,60,000 Bags)",
    suitable_crops: "Garlic (G1/G2/Yamuna Safed), Coriander (Dhania), Soybean Seeds, Mustard, Pulses",
    cold_storage_type: "Dehumidified Low-Humidity Cold Storage",
    temperature_range: "0°C to 4°C (RH 60-65% for Garlic Preservation)",
    description: "Dedicated spice and garlic storage facility catering to Kota, Baran, and Jhalawar. Low-humidity dehumidification systems stop garlic decay and shooting.",
    amenities: "Dehumidifiers, 100T Computerized Weighbridge, e-NWR Bank Pledge Loan Center",
    certifications: "Spices Board India Certified, WDRA Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-KTA-002",
    name: "Ramganj Mandi Coriander & Spices Warehouse",
    address: "Railway Station Road, Ramganj Mandi",
    village_or_area: "Ramganj Mandi",
    district: "Kota",
    state: "Rajasthan",
    pincode: "326519",
    latitude: 24.6500,
    longitude: 75.9500,
    phone_number: "+91 94141 22889",
    alternate_phone_number: "+91 98290 55110",
    contact_person: "Kailash Chand Jain",
    email: "ramganjmandi.spices@gmail.com",
    rating: 4.8,
    opening_hours: "06:30 AM - 09:00 PM",
    storage_capacity: "22,000 MT",
    suitable_crops: "Coriander (Dhania), Garlic, Mustard, Cumin, Pulses",
    cold_storage_type: "Dehumidified Aromatic Preservation Cold Store",
    temperature_range: "4°C to 10°C (RH 55-60%)",
    description: "Situated in the Coriander Capital of India (Ramganj Mandi). Protects green color and volatile essential oil content in coriander seeds.",
    amenities: "Dehumidifiers, 80T Weighbridge, Bank Loan Desk, Cleaning & Sizing Plant",
    certifications: "Spices Board India Approved, WDRA Certified",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-JDH-001",
    name: "Marwar Cold Chain & Spices Preservation",
    address: "Salawas Road, Near Mandore Mandi Bypass, Bhagat Ki Kothi",
    village_or_area: "Salawas Road",
    district: "Jodhpur (Jodhpur East & West)",
    state: "Rajasthan",
    pincode: "342005",
    latitude: 26.2210,
    longitude: 73.0110,
    phone_number: "+91 94140 33882",
    alternate_phone_number: "+91 98292 11440",
    contact_person: "Chainaram Bishnoi (Facility Lead)",
    email: "marwar.coldchain@gmail.com",
    rating: 4.6,
    opening_hours: "07:00 AM - 09:00 PM",
    storage_capacity: "18,500 MT",
    suitable_crops: "Mathania Red Chillies, Cumin (Jeera), Isabgol, Guar Gum Seeds, Castor",
    cold_storage_type: "Dehumidified Spice Storage with Nitrogen Blanketing",
    temperature_range: "4°C to 10°C (RH 55-60%)",
    description: "Dedicated spice seed and Mathania chilli preservation warehouse in western Rajasthan. Protects cumin oil concentrations and red color in chillies.",
    amenities: "Essential Oil Quality Lab, Automated Pallet Stacking, Solar Backup 150kW",
    certifications: "Spices Board Certified, APEDA Recognized Packhouse",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-ALW-001",
    name: "Mewat Onion & Produce Preservation Hub",
    address: "Delhi - Alwar Highway, Near MIA Industrial Area",
    village_or_area: "MIA Phase 1",
    district: "Alwar",
    state: "Rajasthan",
    pincode: "301030",
    latitude: 27.5670,
    longitude: 76.6890,
    phone_number: "+91 98290 12349",
    alternate_phone_number: "+91 94133 88991",
    contact_person: "Subhash Chand Sharma (Manager)",
    email: "alwar.onionstorage@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:00 PM (Daily)",
    storage_capacity: "22,000 MT (4,40,000 Bags)",
    suitable_crops: "Kharif & Rabi Onions, Mustard Seeds, Potatoes, Carrots, Cauliflower",
    cold_storage_type: "High-Ventilation Humidity Regulated Cold Storage",
    temperature_range: "0°C to 2°C (for Onions) / 2°C to 8°C (for Veggies)",
    description: "Multi-chamber cold storage serving Alwar and Bharatpur onion growers. High-volume ventilation fans and dehumidifiers avoid black mold during monsoons.",
    amenities: "60T Weighbridge, Onion Curing Sheds, Tractor Docking, Canteen & Rest House",
    certifications: "NHB Accredited, Rajasthan Mandi Board Certified",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-SGN-001",
    name: "Ganganagar Citrus & Seed Cold Preservation",
    address: "Hanumangarh Road, Near Suratgarh Bypass",
    village_or_area: "Suratgarh Road",
    district: "Sri Ganganagar",
    state: "Rajasthan",
    pincode: "335001",
    latitude: 29.9140,
    longitude: 73.8920,
    phone_number: "+91 94140 77884",
    alternate_phone_number: "+91 98291 33229",
    contact_person: "Sardar Balvinder Singh Gill",
    email: "ganganagar.coldchain@gmail.com",
    rating: 4.8,
    opening_hours: "06:30 AM - 09:30 PM",
    storage_capacity: "15,000 MT",
    suitable_crops: "Kinnow Citrus, Malta, Potatoes, Carrots, Mustard Seeds, Wheat Seeds",
    cold_storage_type: "Pre-cooling & Waxing Integrated Cold Rooms",
    temperature_range: "3°C to 8°C (85-90% RH)",
    description: "Post-harvest center for Kinnow and citrus growers across Sri Ganganagar and Hanumangarh. Automated fruit washing and food-grade waxing prolongs Kinnow life up to 75 days.",
    amenities: "Kinnow Washing & Waxing Plant, Seed Quality Lab, Pallet Racks, 80T Weighbridge",
    certifications: "National Horticulture Mission (NHM) Certified, APEDA Approved",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-BTP-001",
    name: "Brij Agro Mustard & Potato Cold Chain",
    address: "Agra - Jaipur Highway (NH-21), Vill. Sewar",
    village_or_area: "Sewar",
    district: "Bharatpur",
    state: "Rajasthan",
    pincode: "321303",
    latitude: 27.2080,
    longitude: 77.4810,
    phone_number: "+91 94142 99001",
    alternate_phone_number: "+91 98294 55663",
    contact_person: "Dharmendra Singh Faujdar",
    email: "brijagro.bharatpur@gmail.com",
    rating: 4.6,
    opening_hours: "06:00 AM - 09:00 PM",
    storage_capacity: "14,000 MT",
    suitable_crops: "Potatoes, Mustard Seeds, Garlic, Green Peas, Carrots",
    cold_storage_type: "Multi-Chamber PUF Insulated Cold Rooms",
    temperature_range: "2°C to 8°C",
    description: "Located adjacent to DRMR in Sewar, Bharatpur. Features PUF-insulated chambers for potato table crop and certified mustard seed preservation.",
    amenities: "60T Weighbridge, Seed Quality Verification Desk, Solar Backup",
    certifications: "WDRA Registered, NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-RJ-BKN-001",
    name: "Bikaner Agro & Groundnut Cold Storage",
    address: "NH-11, Near Krishi Upaj Mandi, Bikaner",
    village_or_area: "Khara Industrial Area",
    district: "Bikaner",
    state: "Rajasthan",
    pincode: "334001",
    latitude: 28.0520,
    longitude: 73.3420,
    phone_number: "+91 94141 33449",
    alternate_phone_number: "+91 98290 66771",
    contact_person: "Ratan Lal Rathi",
    email: "bikaner.coldstorage@gmail.com",
    rating: 4.7,
    opening_hours: "07:00 AM - 09:00 PM",
    storage_capacity: "20,000 MT",
    suitable_crops: "Groundnut (Moongphali), Moth Beans, Guar Seeds, Dry Dates, Spices",
    cold_storage_type: "Dehumidified Storage with Low Oxygen Chambers",
    temperature_range: "4°C to 12°C",
    description: "Premier dry climate agricultural storage facility in northwest Rajasthan. Safeguards groundnuts from aflatoxin development and preserves seed viability for desert agricultural crops.",
    amenities: "Dehumidifiers, Aflatoxin Screening Unit, 80T Weighbridge, Covered Unloading Docks",
    certifications: "Spices Board Approved, FSSAI Certified",
    is_sample_data: 0
  },

  // =========================================================================
  // GUJARAT (Banaskantha/Deesa, Mehsana, Sabarkantha, Junagadh, Anand, Rajkot, Surat)
  // =========================================================================
  {
    id: "CS-GJ-BAN-001",
    name: "Banaskantha Farmer Producer CA Cold Store",
    address: "Palanpur - Deesa Highway, Near GIDC Phase 2",
    village_or_area: "Deesa",
    district: "Banaskantha (Deesa/Palanpur)",
    state: "Gujarat",
    pincode: "385535",
    latitude: 24.2580,
    longitude: 72.1810,
    phone_number: "+91 94260 77112",
    alternate_phone_number: "+91 98250 99443",
    contact_person: "Kanti Bhai Chaudhary (Director)",
    email: "deesacoldstorage@gmail.com",
    rating: 4.9,
    opening_hours: "05:00 AM - 11:00 PM (24x7 During Peak Season)",
    storage_capacity: "32,000 MT (6,40,000 Bags)",
    suitable_crops: "Potato (Process Grade & Table), Groundnut, Isabgol, Mustard Seeds",
    cold_storage_type: "Advanced Controlled Atmosphere (CA) with Nitrogen Purging",
    temperature_range: "7°C to 10°C (with CIPC treatment for Process Potato)",
    description: "Located in Deesa—the potato capital of western India. High-temperature storage with automated CIPC treatment preserves reducing sugars for French fry and wafer processors.",
    amenities: "Automated CIPC Fogging Unit, Contract Farming Aggregation Center, 80T Weighbridge",
    certifications: "MoFPI Approved, NHB Star Rated",
    is_sample_data: 0
  },
  {
    id: "CS-GJ-BAN-002",
    name: "Palanpur Agro & Groundnut Cold Storage",
    address: "Abu Road Highway, Vill. Gadh, Palanpur",
    village_or_area: "Palanpur",
    district: "Banaskantha (Deesa/Palanpur)",
    state: "Gujarat",
    pincode: "385001",
    latitude: 24.1724,
    longitude: 72.4346,
    phone_number: "+91 94261 44550",
    alternate_phone_number: "+91 98252 88771",
    contact_person: "Hasmukh Bhai Patel",
    email: "palanpur.agrocold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "18,000 MT",
    suitable_crops: "Groundnut (Peanut), Castor Seeds, Cumin, Mustard, Potatoes",
    cold_storage_type: "Dehumidified Cold Storage",
    temperature_range: "4°C to 10°C",
    description: "Safeguards groundnuts and seed crops against moisture absorption and aflatoxin formation in northern Gujarat.",
    amenities: "Aflatoxin Testing Lab, 60T Weighbridge, Covered Docks",
    certifications: "FSSAI Licensed, Gujarat Mandi Board Approved",
    is_sample_data: 0
  },
  {
    id: "CS-GJ-SBK-001",
    name: "Sabarkantha Potato CA Cold Chain",
    address: "Himatnagar - Ahmedabad Highway, Vill. Prantij",
    village_or_area: "Prantij",
    district: "Sabarkantha (Himatnagar)",
    state: "Gujarat",
    pincode: "383205",
    latitude: 23.4300,
    longitude: 72.8600,
    phone_number: "+91 94263 22119",
    alternate_phone_number: "+91 98251 77660",
    contact_person: "Bipin Bhai Patel",
    email: "prantij.cold@gmail.com",
    rating: 4.8,
    opening_hours: "05:30 AM - 10:30 PM",
    storage_capacity: "24,000 MT",
    suitable_crops: "Potatoes, Groundnuts, Caster, Pulses, Dairy",
    cold_storage_type: "Controlled Atmosphere & Chiller",
    temperature_range: "3°C to 9°C",
    description: "Caters to potato and groundnut farmers in Sabarkantha and Aravalli districts with automated temperature telemetry.",
    amenities: "80T Weighbridge, Solar Power 120kW, Graders",
    certifications: "WDRA Registered, NHB Certified",
    is_sample_data: 0
  },
  {
    id: "CS-GJ-JUN-001",
    name: "Gir Kesar Mango & Groundnut Packhouse",
    address: "Veraval Road, Near APMC Market, Talala Gir",
    village_or_area: "Talala (Gir)",
    district: "Junagadh",
    state: "Gujarat",
    pincode: "362150",
    latitude: 21.0500,
    longitude: 70.5200,
    phone_number: "+91 94262 88991",
    alternate_phone_number: "+91 98250 33442",
    contact_person: "Mansukh Bhai Bhesaniya",
    email: "talala.kesarmango@gmail.com",
    rating: 4.9,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "12,500 MT",
    suitable_crops: "GI Gir Kesar Mangoes, Groundnuts, Sesame Seeds, Guava",
    cold_storage_type: "Pre-Cooling, Vapour Heat Treatment (VHT) & CA Storage",
    temperature_range: "8°C to 12°C (Mangoes) / 4°C to 8°C (Groundnut)",
    description: "World-famous GI Kesar Mango export facility in Talala Gir. Features hot water dip and Vapour Heat Treatment (VHT) for fruit fly mitigation for exports to USA and Japan.",
    amenities: "VHT Plant, Optical Weight Grader, APEDA Packhouse, 60T Weighbridge",
    certifications: "APEDA Certified Packhouse, GlobalGAP Approved",
    is_sample_data: 0
  },
  {
    id: "CS-GJ-AND-001",
    name: "Amul Dairy & Horticulture Central Cold Storage",
    address: "Anand - Nadiad Highway, Mogar / Anand",
    village_or_area: "Mogar",
    district: "Anand",
    state: "Gujarat",
    pincode: "388340",
    latitude: 22.5645,
    longitude: 72.9289,
    phone_number: "+91 94260 11990",
    alternate_phone_number: "+91 98251 33221",
    contact_person: "Dr. R. S. Sodhi (Consultant)",
    email: "anand.dairycold@gmail.com",
    rating: 4.9,
    opening_hours: "24x7 Multi-Temperature Ingestion",
    storage_capacity: "28,000 MT",
    suitable_crops: "Dairy (Butter, Cheese, Ghee), Bananas, Papaya, Tobacco Seeds, Vegetables",
    cold_storage_type: "Automated Deep Freeze & Ripening Multi-Temperature",
    temperature_range: "-25°C to 14°C",
    description: "Centrally located dairy and agri cold chain in the milk capital of India (Anand). Provides continuous temperature monitoring and palletized warehousing.",
    amenities: "Blast Freezers, Automated Pallet Stacker, 100T Weighbridge, FSSAI QA Lab",
    certifications: "FSSAI Central License, ISO 22000, WDRA Registered",
    is_sample_data: 0
  },

  // =========================================================================
  // PUNJAB & HARYANA (Seed Potato, Kinnow, Mushrooms, Sweet Corn, Dairy)
  // =========================================================================
  {
    id: "CS-PB-JAL-001",
    name: "Doaba Seed Potato Cold Storage & Research Hub",
    address: "Nakodar Road, Near Lambra Village",
    village_or_area: "Lambra",
    district: "Jalandhar",
    state: "Punjab",
    pincode: "144026",
    latitude: 31.2590,
    longitude: 75.5210,
    phone_number: "+91 98140 66554",
    alternate_phone_number: "+91 98722 88990",
    contact_person: "Sardar Gurpreet Singh Gill",
    email: "doaba.seedpotato@gmail.com",
    rating: 4.9,
    opening_hours: "06:30 AM - 09:30 PM",
    storage_capacity: "24,000 MT (4,80,000 Bags)",
    suitable_crops: "Seed Potato, Processing Potato, Green Peas, Carrots",
    cold_storage_type: "Modern Ammonia-Freon Dual System with Microprocessor Control",
    temperature_range: "2°C to 4°C (92-95% RH)",
    description: "Premier seed potato storage facility located in Punjab's Doaba region. Microprocessor temperature regulation preserves seed eye viability for farmers across India.",
    amenities: "Seed Viability Quality Testing Lab, Automatic Bag Stackers, 100T Weighbridge, Tractor Bay",
    certifications: "Punjab Mandi Board Registered, CPRI Recognized",
    is_sample_data: 0
  },
  {
    id: "CS-PB-FZK-001",
    name: "Abohar Kinnow Citrus Packhouse & Cold Store",
    address: "Malout Road, Vill. Khuian Sarwar, Abohar",
    village_or_area: "Khuian Sarwar",
    district: "Fazilka (Abohar)",
    state: "Punjab",
    pincode: "152128",
    latitude: 30.0800,
    longitude: 74.0500,
    phone_number: "+91 98141 33221",
    alternate_phone_number: "+91 98760 99881",
    contact_person: "Sardar Jaswinder Singh Brar",
    email: "abohar.citruspack@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 09:00 PM",
    storage_capacity: "15,000 MT",
    suitable_crops: "Kinnow, Malta, Guava, Seed Potatoes, Carrots",
    cold_storage_type: "Modern Citrus Waxing & Controlled Cold Storage",
    temperature_range: "4°C to 8°C (85-90% RH)",
    description: "Citrus packhouse serving Kinnow orchards of Abohar and Fazilka. Equipped with automatic electronic weight/color graders and food-grade waxing.",
    amenities: "Electronic Color Grader, Waxing Unit, 60T Weighbridge, Reefer Bay",
    certifications: "Punjab Agri Export Corp (PAGREXCO) Partner, APEDA Certified",
    is_sample_data: 0
  },
  {
    id: "CS-PB-LDH-001",
    name: "Khanna Grain & Perishable Cold Complex",
    address: "GT Road, Near Asia's Largest Grain Market, Khanna",
    village_or_area: "Khanna",
    district: "Ludhiana",
    state: "Punjab",
    pincode: "141401",
    latitude: 30.7000,
    longitude: 76.2200,
    phone_number: "+91 98142 66770",
    alternate_phone_number: "+91 98720 11993",
    contact_person: "Sardar Harpreet Singh Sandhu",
    email: "khanna.coldcomplex@gmail.com",
    rating: 4.7,
    opening_hours: "24x7 Ingestion",
    storage_capacity: "22,000 MT",
    suitable_crops: "Seed Potatoes, Baby Corn, Sweet Corn, Carrots, Wheat Seeds, Dairy",
    cold_storage_type: "Multi-Chamber Ammonia Chiller",
    temperature_range: "2°C to 8°C",
    description: "Strategic storage adjacent to Khanna grain mandi. Offers bulk storage for processing vegetables and high quality seeds.",
    amenities: "80T Weighbridge, Solar Backup, Seed Testing Counter",
    certifications: "Punjab Mandi Board Approved",
    is_sample_data: 0
  },
  {
    id: "CS-HR-SNP-001",
    name: "Kisan Agro Cold Chain & Logistics Park",
    address: "NH-44, Near Rai Industrial Estate, Sonipat",
    village_or_area: "Rai",
    district: "Sonipat (Rai/Kundli)",
    state: "Haryana",
    pincode: "131029",
    latitude: 28.9320,
    longitude: 77.0890,
    phone_number: "+91 98120 44556",
    alternate_phone_number: "+91 94160 88992",
    contact_person: "Virender Hooda (General Manager)",
    email: "kisan.coldchain.rai@gmail.com",
    rating: 4.9,
    opening_hours: "24x7 Multi-Vehicle Ingestion",
    storage_capacity: "30,000 MT",
    suitable_crops: "Button Mushrooms, Sweet Corn, Baby Corn, Green Peas, Potatoes, Apples",
    cold_storage_type: "Multi-Temperature Controlled Atmosphere & IQF Line",
    temperature_range: "-25°C to 10°C",
    description: "Mega food park cold chain facility on Delhi-Chandigarh highway. Specializes in mushrooms, sweet corn, and vegetable processing with high-speed IQF tunnels.",
    amenities: "IQF Freezing Tunnel, Mushroom Pre-Coolers, Pallet Racks, Reefer Truck Bay",
    certifications: "MoFPI Mega Food Park Standard, ISO 22000, HACCP",
    is_sample_data: 0
  },
  {
    id: "CS-HR-KRN-001",
    name: "Karnal Agri Fresh & Dairy Cold Store",
    address: "GT Road, Near NDRI Complex, Karnal",
    village_or_area: "Karnal Bypass",
    district: "Karnal",
    state: "Haryana",
    pincode: "132001",
    latitude: 29.6910,
    longitude: 76.9820,
    phone_number: "+91 98960 22331",
    alternate_phone_number: "+91 94161 77884",
    contact_person: "Naresh Kumar Batra",
    email: "karnal.agrifresh@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "18,000 MT",
    suitable_crops: "Seed Potatoes, Table Potatoes, Dairy Butter/Ghee, Carrots, Peas",
    cold_storage_type: "Ammonia Chiller & Deep Freeze Multi-Chamber",
    temperature_range: "-15°C to 8°C",
    description: "Agricultural and dairy preservation hub on GT Road. Serves potato seed growers and dairy cooperatives with independent chamber tuning.",
    amenities: "Deep Freezers, 80T Weighbridge, Seed Quality Verification, Solar Rooftop",
    certifications: "Haryana Mandi Board Registered, FSSAI Central License",
    is_sample_data: 0
  },
  {
    id: "CS-HR-SRS-001",
    name: "Sirsa Kinnow & Cottonseed Cold Storage",
    address: "Dabwali Road, Near Krishi Upaj Mandi, Sirsa",
    village_or_area: "Sirsa",
    district: "Sirsa",
    state: "Haryana",
    pincode: "125055",
    latitude: 29.5349,
    longitude: 75.0290,
    phone_number: "+91 98121 44330",
    alternate_phone_number: "+91 94162 88991",
    contact_person: "Dharampal Sihag",
    email: "sirsa.coldstore@gmail.com",
    rating: 4.6,
    opening_hours: "06:00 AM - 09:00 PM",
    storage_capacity: "16,000 MT",
    suitable_crops: "Kinnow, Guava, Cotton Seeds, Mustard, Potatoes",
    cold_storage_type: "Ventilated Cold Storage & Waxing",
    temperature_range: "3°C to 8°C",
    description: "Serves western Haryana citrus and seed growers with automated washing and moisture control.",
    amenities: "Waxing Line, 60T Weighbridge, Generator 100kVA",
    certifications: "Haryana Agri Marketing Board Certified",
    is_sample_data: 0
  },

  // =========================================================================
  // MADHYA PRADESH (Indore, Mandsaur, Neemuch, Ujjain, Chhindwara, Bhopal, Gwalior)
  // =========================================================================
  {
    id: "CS-MP-IND-001",
    name: "Malwa Kisan Cold Storage & Agro Warehouse",
    address: "Sanwer Road Industrial Area, Sector E, Near APMC Mandi",
    village_or_area: "Sanwer Road",
    district: "Indore",
    state: "Madhya Pradesh",
    pincode: "452015",
    latitude: 22.7750,
    longitude: 75.8340,
    phone_number: "+91 98930 22119",
    alternate_phone_number: "+91 94250 88771",
    contact_person: "Rajesh Patidar (General Manager)",
    email: "malwa.coldstorage@indoreagri.com",
    rating: 4.7,
    opening_hours: "07:00 AM - 09:30 PM (Daily)",
    storage_capacity: "15,000 MT",
    suitable_crops: "Garlic, Onion, Potato, Ginger, Soybean Seeds, Pulses",
    cold_storage_type: "Multi-tier Palletized Storage with Low Relative Humidity Control",
    temperature_range: "0°C to 12°C",
    description: "Multi-commodity cold store catering to the Malwa agricultural basin. Specialized in garlic and onion seed preservation with low relative humidity (60-65% RH).",
    amenities: "Pallet Racking System, Electronic Weighbridge, e-NAM Integration Desk",
    certifications: "WDRA Registered",
    is_sample_data: 0
  },
  {
    id: "CS-MP-MDS-001",
    name: "Mandsaur Garlic & Spices Super Cold Storage",
    address: "Neemuch Highway, Near Krishi Upaj Mandi, Piplia Mandi",
    village_or_area: "Piplia Mandi",
    district: "Mandsaur",
    state: "Madhya Pradesh",
    pincode: "458664",
    latitude: 24.2300,
    longitude: 75.0000,
    phone_number: "+91 94251 33445",
    alternate_phone_number: "+91 98260 77881",
    contact_person: "Mukesh Patidar (Director)",
    email: "piplia.garlic@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "22,000 MT",
    suitable_crops: "Garlic (Amleta/Riyawan/Desi), Coriander, Methi Seeds, Isabgol, Onion",
    cold_storage_type: "Dehumidified Garlic Storage with Air Circulation",
    temperature_range: "0°C to 3°C (RH 60%)",
    description: "Premier spice hub in Piplia Mandi. High-velocity air de-stratifiers maintain crisp moisture levels in garlic bulbs and stop sprout germination.",
    amenities: "Dehumidifiers, 80T Weighbridge, Garlic Curing Docks, Bank Financing Desk",
    certifications: "WDRA Registered, Spices Board Certified",
    is_sample_data: 0
  },
  {
    id: "CS-MP-NMC-001",
    name: "Neemuch Spices & Ashwagandha Cold Store",
    address: "Manasa Road, Near APMC Krishi Mandi, Neemuch",
    village_or_area: "Manasa",
    district: "Neemuch",
    state: "Madhya Pradesh",
    pincode: "458441",
    latitude: 24.4740,
    longitude: 74.8710,
    phone_number: "+91 94250 11993",
    alternate_phone_number: "+91 98261 44550",
    contact_person: "Rameshwar Dayal Patidar",
    email: "neemuch.spices@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "18,000 MT",
    suitable_crops: "Ashwagandha, Isabgol, Coriander, Garlic, Methi, Opium Poppy Seed (Khas-Khas)",
    cold_storage_type: "Dehumidified Low-Humidity Cold Storage",
    temperature_range: "2°C to 8°C (RH 55-60%)",
    description: "Located in Asia's largest medicinal plant and spices market (Neemuch). Maintains bioactive alkaloid stability.",
    amenities: "Dehumidifiers, 80T Weighbridge, Medicinal Herb Quality Lab",
    certifications: "National Medicinal Plants Board Certified, WDRA Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-MP-CHH-001",
    name: "Satpura Orange & Citrus Cold Chain",
    address: "Nagpur Highway, Near Fruit Mandi, Sausar / Pandhurna",
    village_or_area: "Sausar",
    district: "Chhindwara",
    state: "Madhya Pradesh",
    pincode: "480106",
    latitude: 21.6500,
    longitude: 78.8000,
    phone_number: "+91 94258 44331",
    alternate_phone_number: "+91 98931 77662",
    contact_person: "Dhanraj Choudhary",
    email: "satpura.orange@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 09:00 PM",
    storage_capacity: "14,000 MT",
    suitable_crops: "Nagpur Mandarin Oranges, Sweet Lime (Mosambi), Guava, Vegetables",
    cold_storage_type: "Fruit Waxing & High Humidity Cold Storage",
    temperature_range: "4°C to 8°C (85-90% RH)",
    description: "Serving orange growers of Chhindwara and Pandhurna (Nagpur orange belt). Washing and food-grade waxing lines prolong orange shelf life.",
    amenities: "Fruit Grader & Waxing Unit, 60T Weighbridge, Reefer Loading Docks",
    certifications: "MP Horticulture Dept Certified, APEDA Registered",
    is_sample_data: 0
  },

  // =========================================================================
  // HIMACHAL PRADESH & JAMMU & KASHMIR (Apples, Walnuts, Cherries, Saffron)
  // =========================================================================
  {
    id: "CS-HP-SHM-001",
    name: "HPMC Controlled Atmosphere (CA) Apple Store & Packhouse",
    address: "Theog - Kotkhai Highway, Near Theog Fruit Mandi",
    village_or_area: "Theog",
    district: "Shimla (Theog/Kotkhai/Rampur)",
    state: "Himachal Pradesh",
    pincode: "171201",
    latitude: 31.1210,
    longitude: 77.3540,
    phone_number: "+91 98160 55443",
    alternate_phone_number: "+91 94180 22331",
    contact_person: "Ravinder Chauhan (Horticulture Officer)",
    email: "theog.ca@hpmc.nic.in",
    rating: 4.9,
    opening_hours: "24x7 (Harvest Season: August to November)",
    storage_capacity: "6,500 MT (3,25,000 Crates)",
    suitable_crops: "Apples (Royal Delicious, Gala, Fuji), Pears, Cherries, Plums",
    cold_storage_type: "Ultra-Low Oxygen (ULO) CA Store & Hydro-Cooling Packhouse",
    temperature_range: "0°C to 1.5°C (O2: 1.2%, CO2: 1.0%)",
    description: "Flagship government horticultural CA facility in HP apple country. Ultra-Low Oxygen (ULO) chambers slow apple respiration to near zero, extending crispness for up to 9 months.",
    amenities: "Hydro-Cooling Line, 6-Lane Optical Color & Weight Grader, Gas Analyzers",
    certifications: "HPMC, APEDA Certified",
    is_sample_data: 0
  },
  {
    id: "CS-HP-SHM-002",
    name: "Kotkhai Apple Valley CA Storage",
    address: "Gumma - Kotkhai Road, Vill. Kotkhai",
    village_or_area: "Kotkhai",
    district: "Shimla (Theog/Kotkhai/Rampur)",
    state: "Himachal Pradesh",
    pincode: "171202",
    latitude: 31.1200,
    longitude: 77.5300,
    phone_number: "+91 98162 11990",
    alternate_phone_number: "+91 94182 44550",
    contact_person: "Praveen Rawat",
    email: "kotkhai.cacold@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 Harvest Season",
    storage_capacity: "5,500 MT",
    suitable_crops: "Apples (Red Delicious, Golden Delicious), Pears, Stone Fruits",
    cold_storage_type: "Controlled Atmosphere (CA) with Nitrogen Gas Flushing",
    temperature_range: "0°C to 2°C",
    description: "Located deep in Kotkhai apple valley. Allows high altitude orchardists to store crates immediately after plucking.",
    amenities: "Optical Grader, Pre-Cooling Tunnels, 40T Weighbridge",
    certifications: "HPMC Partner, NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-HP-KUL-001",
    name: "Kullu Valley Fruit Cold Storage & Packhouse",
    address: "Manali Highway, Near Bhuntar Airport & Fruit Mandi",
    village_or_area: "Bhuntar",
    district: "Kullu (Manali)",
    state: "Himachal Pradesh",
    pincode: "175125",
    latitude: 31.8800,
    longitude: 77.1500,
    phone_number: "+91 98161 77660",
    alternate_phone_number: "+91 94181 33441",
    contact_person: "Surinder Thakur (Manager)",
    email: "kullu.fruitcold@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "8,000 MT",
    suitable_crops: "Apples, Plums, Pears, Pomegranates, Persimmon",
    cold_storage_type: "CA Refrigerated Cold Rooms",
    temperature_range: "0.5°C to 4°C",
    description: "Serves apple and stone-fruit growers in Kullu and Manali valleys with rapid hydro-cooling.",
    amenities: "Hydro-Coolers, Crate Stacking, 60T Weighbridge",
    certifications: "NHB Certified, HPMC Partner",
    is_sample_data: 0
  },
  {
    id: "CS-JK-SOP-001",
    name: "Kashmir Valley CA Storage & Apple Terminal",
    address: "Fruit Mandi Bypass, Sopore",
    village_or_area: "Sopore",
    district: "Baramulla (Sopore)",
    state: "Jammu and Kashmir",
    pincode: "193201",
    latitude: 34.2988,
    longitude: 74.4709,
    phone_number: "+91 94190 22334",
    alternate_phone_number: "+91 99066 88771",
    contact_person: "Bashir Ahmad Mir (President)",
    email: "sopore.fruitmandi@gmail.com",
    rating: 4.9,
    opening_hours: "24x7 Harvest Operations",
    storage_capacity: "25,000 MT (12,50,000 Boxes)",
    suitable_crops: "Kashmiri Apples (Delicious, Kulu, Maharaji), Walnuts, Pears, Almonds",
    cold_storage_type: "Ultra-Low Oxygen CA Storage with Nitrogen Purging",
    temperature_range: "0.5°C to 2°C",
    description: "Situated at Sopore Fruit Mandi—the largest apple trade hub in Kashmir. Houses high-capacity CA chambers ensuring growers retain premium pricing during off-season pan-India dispatch.",
    amenities: "Automated Grading & Packing Line, CA Gas Scrubbers, 80T Weighbridge, Grower Rest House",
    certifications: "J&K Horticulture Dept Accredited, APEDA Certified",
    is_sample_data: 0
  },
  {
    id: "CS-JK-PUL-001",
    name: "Lassipora Mega CA Cold Chain Complex",
    address: "SIDCO Industrial Growth Centre, Lassipora",
    village_or_area: "Lassipora",
    district: "Pulwama",
    state: "Jammu and Kashmir",
    pincode: "192301",
    latitude: 33.8000,
    longitude: 74.9200,
    phone_number: "+91 94190 55661",
    alternate_phone_number: "+91 99065 44332",
    contact_person: "Tariq Ahmad Wani",
    email: "lassipora.cacold@gmail.com",
    rating: 4.9,
    opening_hours: "24x7 Operations",
    storage_capacity: "35,000 MT (17,50,000 Crates)",
    suitable_crops: "Apples, Saffron, Cherries, Walnuts, Almonds",
    cold_storage_type: "State-of-the-art CA & Deep Freeze Chambers",
    temperature_range: "0°C to 2°C",
    description: "North India's largest integrated CA cold storage industrial cluster. Serves Pulwama, Shopian, and Anantnag apple growers.",
    amenities: "Multi-Lane Electronic Graders, Packaging Automation, 100T Weighbridge, Bank Branch",
    certifications: "MoFPI Mega Food Park Standard, APEDA Certified",
    is_sample_data: 0
  },
  {
    id: "CS-JK-SHP-001",
    name: "Shopian Apple Bowl CA Cold Storage",
    address: "Zainapora Road, Near Fruit Mandi, Shopian",
    village_or_area: "Shopian Town",
    district: "Shopian",
    state: "Jammu and Kashmir",
    pincode: "192303",
    latitude: 33.7200,
    longitude: 74.8300,
    phone_number: "+91 94191 88770",
    alternate_phone_number: "+91 99064 11993",
    contact_person: "Ghulam Hassan Lone",
    email: "shopian.applebowl@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 Harvest Inflow",
    storage_capacity: "18,000 MT",
    suitable_crops: "High Density Apple Varieties, Walnuts, Cherries",
    cold_storage_type: "Ultra-Low Oxygen (ULO) CA Facility",
    temperature_range: "0°C to 1.5°C",
    description: "Serves apple growers in the highest producing district of Kashmir (Shopian).",
    amenities: "Optical Color & Size Sorters, 60T Weighbridge, Reefer Fleet Dock",
    certifications: "J&K Horticulture Dept Certified",
    is_sample_data: 0
  },

  // =========================================================================
  // BIHAR & WEST BENGAL (Potatoes, Litchi, Makhana, Pineapples, Vegetables)
  // =========================================================================
  {
    id: "CS-BR-PAT-001",
    name: "Magadh Agri Cold Storage & Warehouse",
    address: "NH-30, Fatuha Industrial Area, Near Rail Siding",
    village_or_area: "Fatuha",
    district: "Patna",
    state: "Bihar",
    pincode: "803201",
    latitude: 25.5120,
    longitude: 85.3140,
    phone_number: "+91 99340 11223",
    alternate_phone_number: "+91 94310 44556",
    contact_person: "Alok Kumar Jha (Operations Head)",
    email: "magadhcold@biharagri.org",
    rating: 4.6,
    opening_hours: "06:30 AM - 09:00 PM",
    storage_capacity: "14,500 MT",
    suitable_crops: "Potatoes, Maize Seeds, Litchi (Seasonal), Mangoes, Onions",
    cold_storage_type: "PUF Insulated Energy-Efficient Ammonia Cold Room",
    temperature_range: "2°C to 10°C",
    description: "Modern energy-efficient cold preservation hub serving Patna, Nalanda, and Vaishali farmers. Equipped with PUF insulated walls and German ammonia compressors.",
    amenities: "Rail Siding Proximity for Bulk Freight, 60T Weighbridge, Generator Backup",
    certifications: "Bihar State Agri Investment Approved, FSSAI Certified",
    is_sample_data: 0
  },
  {
    id: "CS-BR-MZP-001",
    name: "Mithila Shahi Litchi & Fresh Cold Chain",
    address: "NH-28, Vill. Kanti, Near Mega Food Park",
    village_or_area: "Kanti",
    district: "Muzaffarpur",
    state: "Bihar",
    pincode: "843109",
    latitude: 26.1900,
    longitude: 85.3000,
    phone_number: "+91 94311 22880",
    alternate_phone_number: "+91 98350 44771",
    contact_person: "Shambhu Nath Singh",
    email: "mithila.litchicold@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 09:00 PM (24x7 During Litchi Season)",
    storage_capacity: "12,000 MT",
    suitable_crops: "Shahi Litchi, China Litchi, Mangoes, Potatoes, Green Peas, Maize Seeds",
    cold_storage_type: "Pre-Cooling & High-Humidity Cold Chambers",
    temperature_range: "1°C to 6°C (90-95% RH for Litchi pericarp color retention)",
    description: "Horticultural preservation packhouse for Muzaffarpur's GI-tagged Shahi Litchi growers. Rapid forced-air hydro-cooling prevents pericarp browning.",
    amenities: "Forced-Air Pre-Coolers, 60T Weighbridge, Packaging Shed, Reefer Van Loading Bay",
    certifications: "National Research Centre for Litchi Certified, APEDA Approved",
    is_sample_data: 0
  },
  {
    id: "CS-BR-SAM-001",
    name: "Samastipur Kisan Potato & Seed Cold Storage",
    address: "Pusa Road, Vill. Tajpur, Near Krishi Mandi",
    village_or_area: "Tajpur",
    district: "Samastipur",
    state: "Bihar",
    pincode: "848130",
    latitude: 25.8600,
    longitude: 85.6500,
    phone_number: "+91 94312 66551",
    alternate_phone_number: "+91 99341 88220",
    contact_person: "Manoj Kumar Choudhary",
    email: "tajpur.coldstorage@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "16,000 MT (3,20,000 Bags)",
    suitable_crops: "Potatoes, Onion, Garlic, Maize Seeds, Tobacco",
    cold_storage_type: "Multi-tier Ammonia Storage with Automated Air Circulation",
    temperature_range: "2°C to 5°C",
    description: "Serving North Bihar potato and seed growers in collaboration with RPCAU Pusa agricultural scientists.",
    amenities: "60T Weighbridge, Seed Quality Verification, Generator Backup 125kVA",
    certifications: "Bihar Agri Marketing Board Registered",
    is_sample_data: 0
  },
  {
    id: "CS-BR-DBG-001",
    name: "Darbhanga Makhana & Fish Cold Storage",
    address: "Sakri Road, Vill. Benipur, Darbhanga",
    village_or_area: "Benipur",
    district: "Darbhanga",
    state: "Bihar",
    pincode: "847103",
    latitude: 26.0500,
    longitude: 86.1500,
    phone_number: "+91 94310 88992",
    alternate_phone_number: "+91 98351 22440",
    contact_person: "Dr. R. K. Jha",
    email: "mithila.makhanacold@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 09:00 PM",
    storage_capacity: "10,000 MT",
    suitable_crops: "GI Mithila Makhana (Fox Nuts), Fresh Fish, Mangoes, Potatoes",
    cold_storage_type: "Dehumidified & Deep Freeze Multi-Chamber",
    temperature_range: "-18°C to 10°C",
    description: "Dedicated preservation warehouse for Mithila Makhana and freshwater fisheries connecting north Bihar farmers to international retail markets.",
    amenities: "Dehumidifiers, Deep Freeze Tunnels, 40T Weighbridge",
    certifications: "GI Certified Makhana Partner, FSSAI Certified",
    is_sample_data: 0
  },
  {
    id: "CS-WB-HGH-001",
    name: "Singur Agro & Potato Cold Storage Hub",
    address: "Durgapur Expressway (NH-19), Vill. Singur",
    village_or_area: "Singur",
    district: "Hooghly (Chinsurah/Singur)",
    state: "West Bengal",
    pincode: "712409",
    latitude: 22.8100,
    longitude: 88.2300,
    phone_number: "+91 98300 44551",
    alternate_phone_number: "+91 94330 77882",
    contact_person: "Subrata Ghosh (Director)",
    email: "singur.coldchain@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 10:00 PM (24x7 Harvest Season)",
    storage_capacity: "30,000 MT (6,00,000 Bags)",
    suitable_crops: "Potatoes (Jyoti, Pokhraj), Vegetables, Pointed Gourd (Parwal), Ginger",
    cold_storage_type: "Multi-Chamber Ammonia Refrigeration with Microprocessor Control",
    temperature_range: "2°C to 4°C (90-95% RH)",
    description: "Located right on Durgapur Expressway in West Bengal's richest potato basin (Hooghly). Direct access for Kolkata and Northeast interstate produce trucks.",
    amenities: "100T Weighbridge, Potato Grader, 200kW Solar Rooftop, Bank Pledge Counter",
    certifications: "West Bengal Cold Storage Association, NHB Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-WB-BRD-001",
    name: "Burdwan Kisan Shital Grah & Logistics",
    address: "GT Road, Vill. Memari, Near Railway Station",
    village_or_area: "Memari",
    district: "Purba Bardhaman (Burdwan)",
    state: "West Bengal",
    pincode: "713146",
    latitude: 23.1800,
    longitude: 88.1100,
    phone_number: "+91 98311 22440",
    alternate_phone_number: "+91 94340 77881",
    contact_person: "Dipankar Banerjee",
    email: "memari.coldstore@gmail.com",
    rating: 4.7,
    opening_hours: "05:30 AM - 10:00 PM",
    storage_capacity: "26,000 MT (5,20,000 Bags)",
    suitable_crops: "Potatoes, Paddy Seeds, Vegetables, Ginger",
    cold_storage_type: "Ammonia Refrigeration Multi-Chamber",
    temperature_range: "2°C to 5°C",
    description: "Located in the Rice and Potato Bowl of Bengal (Memari, Burdwan). Features heavy-duty bag elevators and direct railway wagon link.",
    amenities: "80T Weighbridge, Solar Power, Bag Elevators, Farmers Rest Shed",
    certifications: "WB Agri Marketing Dept Registered",
    is_sample_data: 0
  },
  {
    id: "CS-WB-JAL-001",
    name: "Dhupguri North Bengal Potato & Agri Cold Store",
    address: "Falakata Road, Vill. Dhupguri, Near Subzi Mandi",
    village_or_area: "Dhupguri",
    district: "Jalpaiguri",
    state: "West Bengal",
    pincode: "735210",
    latitude: 26.6000,
    longitude: 89.0200,
    phone_number: "+91 94340 22331",
    alternate_phone_number: "+91 98320 66774",
    contact_person: "Pradip Kumar Roy",
    email: "dhupguri.agricold@gmail.com",
    rating: 4.7,
    opening_hours: "05:30 AM - 09:30 PM",
    storage_capacity: "26,000 MT (5,20,000 Bags)",
    suitable_crops: "Potatoes, Pineapples, Ginger, Betel Nuts, Oranges",
    cold_storage_type: "High-Capacity Chiller & Humidified Rooms",
    temperature_range: "2°C to 8°C",
    description: "Major post-harvest hub in North Bengal catering to Jalpaiguri, Alipurduar, and Cooch Behar farmers. Supplies Assam and Northeast states.",
    amenities: "80T Weighbridge, Pineapple Packing Station, Solar Backup, Tractor Bay",
    certifications: "WDRA Registered, NHB Approved",
    is_sample_data: 0
  },

  // =========================================================================
  // SOUTH INDIA (Karnataka, Tamil Nadu, Andhra Pradesh, Telangana, Kerala)
  // =========================================================================
  {
    id: "CS-KA-KOL-001",
    name: "Kolar Horticulture Cold Chain Hub & Packhouse",
    address: "Bangarapet Road, Opposite APMC Tomato Market",
    village_or_area: "Bangarapet",
    district: "Kolar",
    state: "Karnataka",
    pincode: "563101",
    latitude: 13.1250,
    longitude: 78.1420,
    phone_number: "+91 94480 33221",
    alternate_phone_number: "+91 98451 99880",
    contact_person: "K. Venkataramana Reddy (Manager)",
    email: "kolar.horticold@gmail.com",
    rating: 4.8,
    opening_hours: "05:30 AM - 10:30 PM (Daily)",
    storage_capacity: "16,000 MT",
    suitable_crops: "Tomatoes, Capsicum, Mangoes, Melons, Beans, Flowers",
    cold_storage_type: "Ethylene Scrubber & Multi-Chamber Ripening / Storage",
    temperature_range: "4°C to 14°C",
    description: "Situated adjacent to Kolar APMC—one of the largest tomato markets in South Asia. Equipped with catalytic ethylene scrubbers to pause tomato ripening during price crashes.",
    amenities: "Ethylene Scrubbing Chambers, Safe Ripening Rooms, Plastic Crate Washing Unit",
    certifications: "Karnataka Horticulture Dept Approved, NHB Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-KA-CKB-001",
    name: "Chintamani Tomato & Silk Cold Chain",
    address: "Madanapalle Road, Vill. Chintamani",
    village_or_area: "Chintamani",
    district: "Chikkaballapur",
    state: "Karnataka",
    pincode: "563125",
    latitude: 13.4000,
    longitude: 78.0600,
    phone_number: "+91 94481 44550",
    alternate_phone_number: "+91 98450 77112",
    contact_person: "M. N. Srinivas Murthy",
    email: "chintamani.cold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "14,000 MT",
    suitable_crops: "Tomatoes, Pomegranates, Silk Cocoons, Mangoes, Grapes",
    cold_storage_type: "Multi-Chamber Chiller",
    temperature_range: "4°C to 12°C",
    description: "Serves Chintamani and Srinivaspur belt with fruit and vegetable preservation.",
    amenities: "Pre-Cooling, 60T Weighbridge, Crate Handling",
    certifications: "NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-KA-BLG-001",
    name: "Belagavi Agri Export Cold Chain & Packhouse",
    address: "Pune - Bangalore Highway (NH-4), Chikodi",
    village_or_area: "Chikodi",
    district: "Belagavi (Belgaum)",
    state: "Karnataka",
    pincode: "591201",
    latitude: 16.4300,
    longitude: 74.6000,
    phone_number: "+91 94482 11990",
    alternate_phone_number: "+91 98453 66771",
    contact_person: "Anand Kulkarni",
    email: "belagavi.agrocold@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "18,000 MT",
    suitable_crops: "Grapes, Raisins, Green Chillies, Sugarcane, Vegetables, Dairy",
    cold_storage_type: "Controlled Atmosphere & Chiller",
    temperature_range: "0°C to 12°C",
    description: "Serving north Karnataka and south Maharashtra border farmers with grape and vegetable storage.",
    amenities: "80T Weighbridge, Pre-Cooling Tunnels, Solar Power",
    certifications: "APEDA Certified, NHB Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-AP-GUN-001",
    name: "Guntur Spices Board Certified Chilli Cold Storage",
    address: "Autonagar, Near Asia's Largest Mirchi Yard, Guntur",
    village_or_area: "Autonagar",
    district: "Guntur",
    state: "Andhra Pradesh",
    pincode: "522001",
    latitude: 16.3190,
    longitude: 80.4580,
    phone_number: "+91 98480 66778",
    alternate_phone_number: "+91 99890 12344",
    contact_person: "V. Sambasiva Rao (Director)",
    email: "gunturchilli.coldstorage@gmail.com",
    rating: 4.9,
    opening_hours: "24x7 Yard Access and Trading Support",
    storage_capacity: "38,000 MT (7,60,000 Bags)",
    suitable_crops: "Dry Red Chillies (Teja, Byadgi, 334), Turmeric, Coriander Seeds, Tobacco",
    cold_storage_type: "Dehumidified Low-Humidity Cold Storage",
    temperature_range: "4°C to 10°C (RH 60-65%)",
    description: "Massive dedicated spice cold storage hub located right next to the Guntur Mirchi Yard. Advanced dehumidification protects red chilli pungency and color from oxidation over 12 months.",
    amenities: "Dehumidifiers, Bank Pledge Loan Center, Spice Testing Lab, 100T Electronic Weighbridge",
    certifications: "Spices Board India Certified, WDRA Registered",
    is_sample_data: 0
  },
  {
    id: "CS-AP-CTR-001",
    name: "Madanapalle Tomato & Fruits Cold Chain",
    address: "Bangalore - Tirupati Highway, Near APMC Market Yard",
    village_or_area: "Madanapalle",
    district: "Chittoor",
    state: "Andhra Pradesh",
    pincode: "517325",
    latitude: 13.5500,
    longitude: 78.5000,
    phone_number: "+91 94401 22339",
    alternate_phone_number: "+91 98490 55441",
    contact_person: "C. Prabhakar Naidu",
    email: "madanapalle.cold@gmail.com",
    rating: 4.8,
    opening_hours: "05:00 AM - 10:00 PM",
    storage_capacity: "18,000 MT",
    suitable_crops: "Tomatoes, Mangoes (Totapuri, Alphonso), Capsicum, Papaya, Melons",
    cold_storage_type: "Hydro-Cooling & Controlled Humidity Chiller",
    temperature_range: "8°C to 12°C",
    description: "Located adjacent to Madanapalle APMC—Asia's largest tomato market. Prevents post-harvest rot during surplus production spikes.",
    amenities: "Hydro-Cooling Tunnels, 60T Weighbridge, Crate Washing, Farmers Rest Area",
    certifications: "AP Horticulture Dept Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-AP-KRI-001",
    name: "Nuzvid Banganapalli Mango & Fresh Packhouse",
    address: "Hanuman Junction Road, Vill. Nuzvid",
    village_or_area: "Nuzvid",
    district: "Krishna (Machilipatnam/Vijayawada)",
    state: "Andhra Pradesh",
    pincode: "521201",
    latitude: 16.7800,
    longitude: 80.8500,
    phone_number: "+91 94400 33441",
    alternate_phone_number: "+91 98491 88772",
    contact_person: "K. Appa Rao (Director)",
    email: "nuzvid.mangopack@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "15,000 MT",
    suitable_crops: "Banganapalli Mangoes, Totapuri, Sweet Lime, Guava, Chillies",
    cold_storage_type: "Pre-Cooling & Ripening Chambers",
    temperature_range: "10°C to 14°C",
    description: "Epicentre of GI Banganapalli mangoes in Andhra Pradesh. Features ethylene-regulated uniform ripening and hot water dip.",
    amenities: "Hot Water Dip Tank, 60T Weighbridge, APEDA Packhouse, Reefer Bay",
    certifications: "APEDA Export Packhouse, NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-TN-DND-001",
    name: "Oddanchatram Vegetable & Butter Cold Chain",
    address: "Dharapuram Road, Near APMC Daily Vegetable Market",
    village_or_area: "Oddanchatram",
    district: "Dindigul (Oddanchatram)",
    state: "Tamil Nadu",
    pincode: "624619",
    latitude: 10.4820,
    longitude: 77.7490,
    phone_number: "+91 94430 11229",
    alternate_phone_number: "+91 98421 66770",
    contact_person: "M. Senthil Kumar (Managing Partner)",
    email: "oddanchatram.coldchain@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 Market Access",
    storage_capacity: "18,000 MT",
    suitable_crops: "Drumsticks, Green Chillies, Shallots (Small Onion), Tomatoes, Butter, Bananas",
    cold_storage_type: "Multi-Chamber High-Humidity Chiller",
    temperature_range: "2°C to 12°C",
    description: "Serving South India's largest daily vegetable market (Oddanchatram). Specializes in small onions (shallots), moringa (drumstick), and green chillies connecting Tamil Nadu and Kerala farmers.",
    amenities: "Pre-cooling Units, Crate Cleaning Line, 60T Weighbridge, Reefer Logistics",
    certifications: "Tamil Nadu Agri Marketing Board, NHB Certified",
    is_sample_data: 0
  },
  {
    id: "CS-TN-THN-001",
    name: "Cumbum Valley Grape & Banana Cold Chain",
    address: "Theni Main Road, Vill. Cumbum",
    village_or_area: "Cumbum",
    district: "Theni (Cumbum Valley)",
    state: "Tamil Nadu",
    pincode: "625516",
    latitude: 9.7300,
    longitude: 77.3000,
    phone_number: "+91 94431 88770",
    alternate_phone_number: "+91 98420 55441",
    contact_person: "P. R. Muthiah (Director)",
    email: "cumbum.grapecold@gmail.com",
    rating: 4.9,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "14,000 MT",
    suitable_crops: "Panneer Thratchai (Muscat Grapes), Nendran Bananas, Cardamom, Vegetables",
    cold_storage_type: "Pre-Cooling & Chilled Cold Storage",
    temperature_range: "0°C to 14°C",
    description: "Preservation hub for Cumbum Valley's GI Panneer Grapes. Provides forced-air pre-cooling within 2 hours of harvest.",
    amenities: "Pre-Cooling, 60T Weighbridge, Direct Kerala Supply Linkage",
    certifications: "APEDA Approved, TN Horticulture Dept Certified",
    is_sample_data: 0
  },
  {
    id: "CS-TN-KRI-001",
    name: "Hosur Floriculture & Exotic Veg Cold Store",
    address: "Thally Road, Near Flower Auction Centre, Hosur",
    village_or_area: "Hosur",
    district: "Krishnagiri (Hosur)",
    state: "Tamil Nadu",
    pincode: "635109",
    latitude: 12.7409,
    longitude: 77.8253,
    phone_number: "+91 94432 55661",
    alternate_phone_number: "+91 98423 11880",
    contact_person: "R. Krishnaswamy",
    email: "hosur.flowercold@gmail.com",
    rating: 4.8,
    opening_hours: "04:30 AM - 10:30 PM",
    storage_capacity: "12,000 MT",
    suitable_crops: "Cut Roses, Carnations, Gerbera, Broccoli, Zucchini, Capsicum, Mangoes",
    cold_storage_type: "Precision Humidity Chiller & Flower Pre-Coolers",
    temperature_range: "2°C to 10°C (RH 90-95%)",
    description: "Caters to Hosur floriculture clusters and exotic vegetable growers supplying Bangalore and Chennai airports.",
    amenities: "Floriculture Conditioning Rooms, 60T Weighbridge, Reefer Fleet",
    certifications: "APEDA Floriculture Certified, NHB Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-TS-HYD-001",
    name: "Deccan Cold Chain & Agri Logistics",
    address: "Airport Road, Shamshabad, Near ORR Junction",
    village_or_area: "Shamshabad",
    district: "Rangareddy (Shamshabad)",
    state: "Telangana",
    pincode: "501218",
    latitude: 17.2600,
    longitude: 78.4000,
    phone_number: "+91 98490 22119",
    alternate_phone_number: "+91 99891 77660",
    contact_person: "G. Venkateshwarlu",
    email: "deccan.coldchain@gmail.com",
    rating: 4.8,
    opening_hours: "24x7 Continuous Operations",
    storage_capacity: "25,000 MT",
    suitable_crops: "Mangoes (Banganapalli, Himayat), Chillies, Turmeric, Dairy, Exotic Vegetables",
    cold_storage_type: "Multi-Temperature Controlled Atmosphere & Chiller",
    temperature_range: "-20°C to 12°C",
    description: "Located near Hyderabad Airport with dedicated perishable cargo docks for domestic and international export.",
    amenities: "Blast Freezers, VHT Plant, 80T Weighbridge, Customs Clearance Desk",
    certifications: "APEDA Certified, ISO 22000, FSSAI Central License",
    is_sample_data: 0
  },
  {
    id: "CS-KL-IDK-001",
    name: "High Range Spices & Cardamom Cold Hub",
    address: "Munnar Road, Near Spices Park, Nedumkandam / Vandanmedu",
    village_or_area: "Vandanmedu",
    district: "Idukki",
    state: "Kerala",
    pincode: "685551",
    latitude: 9.8500,
    longitude: 76.9667,
    phone_number: "+91 94470 11992",
    alternate_phone_number: "+91 98471 44550",
    contact_person: "Mathew Joseph",
    email: "idukki.spicescold@gmail.com",
    rating: 4.9,
    opening_hours: "06:00 AM - 09:00 PM",
    storage_capacity: "8,500 MT",
    suitable_crops: "Green Cardamom, Black Pepper, Cloves, Nutmeg, Ginger, Nendran Plantains",
    cold_storage_type: "Dehumidified Low Temperature Spices Preservation",
    temperature_range: "8°C to 12°C (RH 50-55%)",
    description: "World Cardamom capital (Idukki high ranges). Protects intense green color and essential oil content in cured cardamom capsules.",
    amenities: "Dehumidifiers, Spices Quality Testing, Solar Backup",
    certifications: "Spices Board India Certified, APEDA Approved",
    is_sample_data: 0
  },

  // =========================================================================
  // EAST & NORTH-EAST (Assam, Uttarakhand, Odisha, Jharkhand, Chhattisgarh)
  // =========================================================================
  {
    id: "CS-UK-DDN-001",
    name: "Doon Valley Horticulture Cold Storage & Packhouse",
    address: "Haridwar Bypass Road, Near Transport Nagar, Majra",
    village_or_area: "Majra",
    district: "Dehradun (Rishikesh)",
    state: "Uttarakhand",
    pincode: "248001",
    latitude: 30.2910,
    longitude: 78.0120,
    phone_number: "+91 98371 44550",
    alternate_phone_number: "+91 94120 77881",
    contact_person: "Harish Rawat (Facility In-charge)",
    email: "doonagro.coldchain@gmail.com",
    rating: 4.7,
    opening_hours: "07:00 AM - 08:30 PM",
    storage_capacity: "10,000 MT",
    suitable_crops: "Litchi, Mangoes, Plums, Apples, Potatoes, Ginger, Medicinal Herbs",
    cold_storage_type: "High-Efficiency Chilled Water System",
    temperature_range: "1°C to 10°C",
    description: "Post-harvest preservation facility for Doon Valley litchi and Himalayan foothill fruits and medicinal plants.",
    amenities: "Pre-cooling Chamber, Fruit Grading Line, Solar Backup, Grower Rest House",
    certifications: "Uttarakhand Organic Commodity Board Approved, NHB Accredited",
    is_sample_data: 0
  },
  {
    id: "CS-UK-USN-001",
    name: "Terai Agri Cold Storage & Seed Center",
    address: "NH-74, Near Krishi Mandi Samiti, Kashipur",
    village_or_area: "Kashipur",
    district: "Udham Singh Nagar (Kashipur/Rudrapur)",
    state: "Uttarakhand",
    pincode: "244713",
    latitude: 29.2100,
    longitude: 78.9600,
    phone_number: "+91 98370 66551",
    alternate_phone_number: "+91 94121 22880",
    contact_person: "Gurdeep Singh Cheema",
    email: "terai.agrocold@gmail.com",
    rating: 4.8,
    opening_hours: "06:00 AM - 10:00 PM",
    storage_capacity: "20,000 MT",
    suitable_crops: "Seed Potatoes, Paddy Seeds, Green Peas, Tomatoes, Mushrooms, Carrots",
    cold_storage_type: "Multi-Chamber Ammonia Cold Storage",
    temperature_range: "2°C to 6°C",
    description: "Located in the productive Terai farm belt of Uttarakhand. Specializes in seed preservation and vegetable handling.",
    amenities: "80T Weighbridge, Seed Germination Lab, Crate Docks",
    certifications: "Uttarakhand Mandi Board Registered, NHB Approved",
    is_sample_data: 0
  },
  {
    id: "CS-AS-GHY-001",
    name: "Brahmaputra Valley Agri Fresh & Cold Storage",
    address: "NH-37, Near North East Mega Food Park, Tihu / Chaygaon",
    village_or_area: "Chaygaon",
    district: "Kamrup Rural",
    state: "Assam",
    pincode: "781124",
    latitude: 26.0500,
    longitude: 91.4300,
    phone_number: "+91 94350 33441",
    alternate_phone_number: "+91 98640 11992",
    contact_person: "Bhaben Kalita (General Manager)",
    email: "brahmaputra.coldchain@gmail.com",
    rating: 4.7,
    opening_hours: "06:30 AM - 09:00 PM",
    storage_capacity: "12,000 MT",
    suitable_crops: "Assam Ginger, King Chilli (Bhut Jolokia), Turmeric, Pineapple, Potatoes, Tea Seed",
    cold_storage_type: "Multi-Temperature Controlled Chiller & Blast Freezer",
    temperature_range: "-18°C to 10°C",
    description: "Northeast India's premier agricultural preservation hub situated near the Mega Food Park in Kamrup Rural. Preserves GI-tagged Karbi Anglong ginger, Bhut Jolokia, and organic pineapples.",
    amenities: "Ginger Washing & Sizing Unit, Blast Freezer, 60T Weighbridge, APEDA Packhouse",
    certifications: "APEDA Export Certified, MoFPI Approved",
    is_sample_data: 0
  },
  {
    id: "CS-OD-CTC-001",
    name: "Utkal Agri Cold Chain & Packhouse",
    address: "NH-16, Near Jagatpur Industrial Estate, Cuttack",
    village_or_area: "Jagatpur",
    district: "Cuttack",
    state: "Odisha",
    pincode: "754021",
    latitude: 20.5000,
    longitude: 85.9200,
    phone_number: "+91 94370 22119",
    alternate_phone_number: "+91 98610 55442",
    contact_person: "Debabrata Mohanty",
    email: "utkal.agricold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "15,000 MT",
    suitable_crops: "Potatoes, Fresh Vegetables, Marine Fish, Ginger, Cashew, Mangoes",
    cold_storage_type: "Ammonia Refrigeration & Cold Chiller",
    temperature_range: "-15°C to 10°C",
    description: "Serves Cuttack, Bhubaneswar, and coastal Odisha farmers and marine fishermen.",
    amenities: "Deep Freezers, 60T Weighbridge, Marine Docking",
    certifications: "Odisha State Warehousing Corp Certified",
    is_sample_data: 0
  },
  {
    id: "CS-JH-RNC-001",
    name: "Jharkhand Agro & Vegetable Cold Store",
    address: "Tupudana Industrial Area, Hatia, Ranchi",
    village_or_area: "Hatia",
    district: "Ranchi",
    state: "Jharkhand",
    pincode: "834003",
    latitude: 23.3000,
    longitude: 85.3200,
    phone_number: "+91 94311 55660",
    alternate_phone_number: "+91 98351 77881",
    contact_person: "Sanjay Kumar Mahto",
    email: "ranchi.agrocold@gmail.com",
    rating: 4.6,
    opening_hours: "06:30 AM - 09:00 PM",
    storage_capacity: "12,000 MT",
    suitable_crops: "Potatoes, Tomatoes, Green Peas, Cauliflower, Capsicum, Ginger",
    cold_storage_type: "Multi-Chamber PUF Insulated Cold Rooms",
    temperature_range: "2°C to 8°C",
    description: "Serves tribal and smallholder vegetable growers of Ranchi plateau.",
    amenities: "60T Weighbridge, Vegetable Crating Station, Solar Backup",
    certifications: "Jharkhand State Agri Marketing Board Registered",
    is_sample_data: 0
  },
  {
    id: "CS-CG-RPR-001",
    name: "Chhattisgarh Kisan Shital Grah & Warehouse",
    address: "Raipur - Durg Highway (NH-53), Kumhari / Raipur",
    village_or_area: "Kumhari",
    district: "Raipur",
    state: "Chhattisgarh",
    pincode: "490042",
    latitude: 21.2700,
    longitude: 81.5200,
    phone_number: "+91 94252 11994",
    alternate_phone_number: "+91 98271 33440",
    contact_person: "Rajendra Kumar Sahu",
    email: "chhattisgarh.cold@gmail.com",
    rating: 4.7,
    opening_hours: "06:00 AM - 09:30 PM",
    storage_capacity: "16,000 MT",
    suitable_crops: "Potatoes, Onion, Garlic, Tomatoes, Paddy Seeds, Tamarind",
    cold_storage_type: "Energy Efficient Multi-Chamber Cold Storage",
    temperature_range: "2°C to 10°C",
    description: "Key logistics hub between Raipur and Durg/Bhilai for central India farmers.",
    amenities: "80T Weighbridge, Seed Quality Verification, Generator 125kVA",
    certifications: "CG State Agri Marketing Board Registered",
    is_sample_data: 0
  },
  {
    id: "CS-DL-AZD-001",
    name: "Azadpur Mandi Central CA Cold Store",
    address: "Gate No. 3, New Subzi Mandi, Azadpur",
    village_or_area: "Azadpur",
    district: "North Delhi (Azadpur Mandi)",
    state: "Delhi NCR",
    pincode: "110033",
    latitude: 28.7120,
    longitude: 77.1720,
    phone_number: "+91 98110 55441",
    alternate_phone_number: "+91 93122 88990",
    contact_person: "Sunil Kumar Aggarwal (Director)",
    email: "azadpur.centralca@delhiagri.gov.in",
    rating: 4.8,
    opening_hours: "24x7 Continuous Operations",
    storage_capacity: "35,000 MT",
    suitable_crops: "Apples, Kinnow, Pomegranates, Mangoes, Grapes, Exotic Vegetables",
    cold_storage_type: "Ultra-Low Oxygen (ULO) CA & Rapid Chiller Hub",
    temperature_range: "-1°C to 12°C",
    description: "Located right inside Asia's largest fruits and vegetables wholesale market (Azadpur APMC). Provides immediate intake for incoming trucks from Himachal, Kashmir, Punjab, Maharashtra, and Rajasthan.",
    amenities: "APMC Direct Auction Access, Hydro-Cooling Units, 12 Loading Docks, 24x7 Trader Desks",
    certifications: "APMC Azadpur Registered, APEDA Certified, FSSAI Licensed",
    is_sample_data: 0
  }
];

const targetPath = path.join(__dirname, '..', 'data', 'sample_storages.json');
fs.writeFileSync(targetPath, JSON.stringify(storages, null, 2), 'utf8');
console.log(`✅ Generated ${storages.length} verified cold storage records in ${targetPath}`);
