"""initial_schema_postgresql_pgvector

Revision ID: ec3f0819e51f
Revises: 
Create Date: 2026-09-03 13:04:55.673265

"""
from alembic import op
import sqlalchemy as sa


revision = 'ec3f0819e51f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('sensor', sa.String(length=50), nullable=False),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_detections_device_id'), 'animal_detections', ['device_id'], unique=False)
    op.create_index('ix_animal_detections_device_timestamp', 'animal_detections', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_animal_detections_id'), 'animal_detections', ['id'], unique=False)
    op.create_index(op.f('ix_animal_detections_sensor'), 'animal_detections', ['sensor'], unique=False)
    op.create_index(op.f('ix_animal_detections_timestamp'), 'animal_detections', ['timestamp'], unique=False)
    op.create_table('device_status',
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_device_status_device_id'), 'device_status', ['device_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_doc_type'), 'document_chunks', ['doc_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('mandi_price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('target_percentage_change', sa.Float(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mandi_alerts_user_commodity', 'mandi_price_alerts', ['user_id', 'commodity', 'status'], unique=False)
    op.create_index(op.f('ix_mandi_price_alerts_commodity'), 'mandi_price_alerts', ['commodity'], unique=False)
    op.create_index(op.f('ix_mandi_price_alerts_id'), 'mandi_price_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_price_alerts_status'), 'mandi_price_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_mandi_price_alerts_user_id'), 'mandi_price_alerts', ['user_id'], unique=False)
    op.create_table('sensor_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('sensor', sa.String(length=50), nullable=False),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'sensor', name='uq_device_sensor')
    )
    op.create_index(op.f('ix_sensor_status_device_id'), 'sensor_status', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_status_id'), 'sensor_status', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_status_sensor'), 'sensor_status', ['sensor'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'LABOR', 'BUYER', 'SELLER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('consent_voice_storage', sa.Boolean(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'SOWN', 'GROWING', 'FLOWERING', 'READY', 'HARVESTED', name='cropstatus'), nullable=False),
    sa.Column('sowing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_harvest_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_yield_quintals', sa.Float(), nullable=True),
    sa.Column('actual_yield_quintals', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.create_index(op.f('ix_crops_name'), 'crops', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crops_name'), table_name='crops')
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensor_status_sensor'), table_name='sensor_status')
    op.drop_index(op.f('ix_sensor_status_id'), table_name='sensor_status')
    op.drop_index(op.f('ix_sensor_status_device_id'), table_name='sensor_status')
    op.drop_table('sensor_status')
    op.drop_index(op.f('ix_mandi_price_alerts_user_id'), table_name='mandi_price_alerts')
    op.drop_index(op.f('ix_mandi_price_alerts_status'), table_name='mandi_price_alerts')
    op.drop_index(op.f('ix_mandi_price_alerts_id'), table_name='mandi_price_alerts')
    op.drop_index(op.f('ix_mandi_price_alerts_commodity'), table_name='mandi_price_alerts')
    op.drop_index('ix_mandi_alerts_user_commodity', table_name='mandi_price_alerts')
    op.drop_table('mandi_price_alerts')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_doc_type'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_device_status_device_id'), table_name='device_status')
    op.drop_table('device_status')
    op.drop_index(op.f('ix_animal_detections_timestamp'), table_name='animal_detections')
    op.drop_index(op.f('ix_animal_detections_sensor'), table_name='animal_detections')
    op.drop_index(op.f('ix_animal_detections_id'), table_name='animal_detections')
    op.drop_index('ix_animal_detections_device_timestamp', table_name='animal_detections')
    op.drop_index(op.f('ix_animal_detections_device_id'), table_name='animal_detections')
    op.drop_table('animal_detections')
    # ### end Alembic commands ###
